<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Czech.
 * All the prompts are in ISO-8859-2 encoding.
 *
 * @package Engine
 * @subpackage Localization
 * @author Vit Popelka
 */

$resource_czech = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'V¹echna pole oznaèená jako povinná musí být vyplnìna.',
    'Výchozí hodnota musí být v rozmezí %1 a¾ %2.',
    'Úèet je zablokován.',
    'Úèet je uzamèen.',
    'Neplatné u¾ivatelské jméno.',
    'Úèet se zadaným u¾ivatelským jménem ji¾ existuje.',
    'Neplatný e-mail.',
    'Hesla se neshodují.',
    'Heslo musí být dlouhé alespoò %1 znakù.',
    'Projekt se zadaným názvem ji¾ existuje.',
    /* 210 */
    'Skupina se zadaným jménem ji¾ existuje.',
    '©ablona se zadaným jménem nebo pøedponou ji¾ existuje.',
    'Stav se zadaným jménem nebo zkratkou ji¾ existuje.',
    'Pole se zadaným jménem ji¾ existuje.',
    'Neplatné èíslo.',
    'Èíslo musí být v rozmezí %1 a¾ %2.',
    'Hodnota "%1" musí být v rozmezí %2 a¾ %3.',
    'Maximální hodnota musí být vìt¹í ne¾ minimální.',
    'Velikost souboru je vìt¹í ne¾ velikost povolená parametrem "upload_max_filesize" v souboru "php.ini".',
    'Velikost souboru nesmí být vìt¹í ne¾ %1 kB.',
    /* 220 */
    'Soubor byl nahrán jen èásteènì.',
    '®ádný soubor nebyl nahrán.',
    'Chybí doèasná slo¾ka.',
    'Pøíloha se zadaným jménem ji¾ existuje.',
    'Záznam nenalezen.',
    'Filtr se zadaným jménem ji¾ existuje.',
    'Neplatné datum.',
    'Datum musí být v rozmezí %1 a¾ %2.',
    'Neplatný èas.',
    'Èas musí být v rozmezí %1 a¾ %2.',
    /* 230 */
    'Pøedplatné se zadaným jménem ji¾ existuje.',
    'Upomínka se zadaným jménem ji¾ existuje.',
    'Pøipomenutí úspì¹nì odesláno.',
    'Pohled se zadaným jménem ji¾ existuje.',
    'Sloupec se zadaným jménem ji¾ existuje.',
    'Nepodaøilo se zapsat soubor na disk.',
    'Nahrání souboru zastaveno roz¹íøením.',
    'Musí být povolena podpora JavaScriptu.',
    'To je automaticky generovaná zpráva, prosím, neodpovídejte na ni.',
    'Po¾adovaný podøízený záznam ji¾ existuje.',
    /* 240 */
    'Sada filtrù se zadaným jménem ji¾ existuje.',
    'Pohled nemù¾e mít více ne¾ %1 sloupcù.',
    'Hodnota "%1" neodpovídá definovanému formátu.',
    'U¾ivatel není pøihlá¹en.',
    'Neznámé u¾ivatelské jméno nebo chybné heslo.',
    'Neznámý typ ovìøování.',
    'Neznámá chyba.',
    'Chyba XML parseru.',
    'Chyba pøipojení k databázi.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Jste si jisti, ¾e chcete odstranit v¹echny vybrané pohledy?',
    'Jste si jisti, ¾e chcete smazat tento úèet?',
    'Jste si jisti, ¾e chcete smazat tento projekt?',
    'Jste si jisti, ¾e chcete vymazat tuto skupinu?',
    'Jste si jisti, ¾e chcete smazat tuto ¹ablonu?',
    'Jste si jisti, ¾e chcete smazat tento stav?',
    'Jste si jisti, ¾e chcete smazat toto pole?',
    'Jste si jisti, ¾e chcete odlo¾it tento záznam?',
    'Jste si jisti, ¾e chcete obnovit tento záznam?',
    'Jste si jisti, ¾e chcete pøiøadit tento záznam?',
    /* 310 */
    'Jste si jisti, ¾e chcete odstranit v¹echny vybrané filtry?',
    'Jste si jisti, ¾e chcete smazat v¹echny vybrané pøedplatné?',
    'Jste si jisti, ¾e chcete poslat pøipomínku?',
    'Jste si jisti, ¾e chcete smazat tuto pøipomínku?',
    'Jste si jisti, ¾e chcete smazat tento sloupec?',
    'Jste si jisti, ¾e se chcete odhlásit?',
    'Jste si jisti, ¾e chcete odstranit v¹echny vybrané sady filtrù?',
    'Jste si jisti, ¾e chcete smazat tento záznam?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'èe¹tina',
    'Pøihlásit se',
    '  OK  ',
    'Zru¹it',
    'Ulo¾it',
    'Zpìt',
    'Dal¹í',
    'Vytvoøit',
    'Zmìnit',
    'Smazat',
    /* 1010 */
    'Záznamy',
    'Úèty',
    'Projekty',
    'Zmìnit heslo',
    'Pole stavu "%1"',
    '¾ádný/é',
    'Celkem:',
    'ulo¾it heslo',
    'Informace o úètu',
    'U¾ivatelské jméno',
    /* 1020 */
    'Celé jméno',
    'E-mail',
    'Oprávnìní',
    'administrátor',
    'u¾ivatel',
    'Popis',
    'Heslo',
    'Potvrzení',
    'zakázán',
    'uzamèen',
    /* 1030 */
    'Nový úèet',
    'Úèet "%1"',
    'Informace o projektu',
    'Jméno projektu',
    'Datum a èas zahájení',
    'pozastaven',
    'Nový projekt',
    'Projekt "%1"',
    'Skupiny',
    'Informace o skupinì',
    /* 1040 */
    'Název skupiny',
    'Nová skupina',
    'Skupina "%1"',
    'Èlenství',
    'Ostatní',
    'Èlenové',
    '©ablony',
    'Informace o ¹ablonì',
    'Jméno ¹ablony',
    'Prefix',
    /* 1050 */
    'Nová ¹ablona',
    '©ablona "%1"',
    'Stavy',
    'Informace o stavu',
    'Jméno stavu',
    'Zkratka',
    'Typ stavu',
    'poèáteèní',
    'standardní',
    'koncový',
    /* 1060 */
    'Odpovìdnost',
    'zachovat',
    'pøiøadit',
    'odstranit',
    'Nový stav',
    'Stav "%1"',
    'Vytvoøit standardní',
    'Vytvoøit koncový',
    'Pøechody',
    'Oprávnìní',
    /* 1070 */
    'Vytvoøit poèáteèní',
    'Pøípustný',
    'Pole',
    'Informace o poli',
    'Poøadí',
    'Jméno pole',
    'Typ pole',
    'èíslo',
    'øetìzec',
    'víceøádkový øetìzec',
    /* 1080 */
    'Povinný',
    'ano',
    'ne',
    'Min. hodnota',
    'Max. hodnota',
    'Max. délka',
    'povinný',
    'Nové pole (krok %1/%2)',
    'Pole "%1"',
    'pouze pro ètení',
    /* 1090 */
    'ètení i zápis',
    'V¹eobecné informace',
    'ID',
    'Projekt',
    '©ablona',
    'Stav',
    'Stáøí',
    'Nový záznam (krok %1/%2)',
    'Záznam "%1"',
    'Zobraz',
    /* 1100 */
    'Historie',
    'Odlo¾it',
    'Pokraèovat',
    'Pøiøadit',
    'Zmìnit stav',
    'Datum vzniku',
    'Pùvodce',
    'Záznam je vytvoøen ve stavu "%1".',
    'Záznam je pøiøazen u¾ivateli %1.',
    'Záznam je upraven.',
    /* 1110 */
    'Stav je zmìnìn na "%1".',
    'Záznam je odlo¾en do %1.',
    'Záznam je obnoven.',
    'Soubor "%1" je pøilo¾en.',
    'Soubor "%1" je odstranìn.',
    'oprávnìní vytvoøit nový záznam',
    'oprávnìní modifikovat záznam',
    'oprávnìní odlo¾it záznam',
    'oprávnìní obnovit záznam',
    'oprávnìní pøerozdìlit záznam',
    /* 1120 */
    'oprávnìní zmìnit stav záznamu',
    'oprávnìní pøipojit soubor',
    'oprávnìní odstranit soubor',
    'Jazyk',
    'Pøidat komentáø',
    'Komentáø je pøidán.',
    'oprávnìní pøidat komentáø',
    'Komentáø',
    'Pøipojit soubor',
    'Odstranit soubor',
    /* 1130 */
    'Pøíloha',
    'Název pøílohy',
    'Soubor',
    'Pøílohy',
    '®ádná pole.',
    'Kritické stáøí',
    'Èas zmrazení',
    'Zmìny',
    'Stará hodnota',
    'Nová hodnota',
    /* 1140 */
    'za¹krtávací pole',
    'záznam',
    'seznam',
    'Polo¾ky seznamu',
    '%1 Kb',
    'Filtry',
    'Jméno filtru',
    'V¹echny projekty',
    'V¹echny ¹ablony',
    'V¹echny stavy',
    /* 1150 */
    'Zobrazit záznam',
    'Zobrazit pouze vytvoøené ...',
    'Zobrazit pouze pøidìlené ...',
    'zobrazit pouze neuzavøené',
    'Pøedmìt',
    'Hledat',
    'Parametry vyhledávání',
    'Výsledky vyhledávání',
    'Hledaný text',
    'hledání v polích',
    /* 1160 */
    'hledání v komentáøích',
    'Status',
    'aktivní',
    'Pøedplatné',
    'oznámení pøi vytvoøení záznamu',
    'oznámení pøi pøiøazení záznamu',
    'oznámení pøi modifikaci záznamu',
    'oznámení pøi zmìnì stavu',
    'oznámení pøi odlo¾ení záznamu',
    'oznámení pøi obnovení záznamu',
    /* 1170 */
    'oznámení pøi pøidání komentáøe',
    'oznámení pøi pøipojení pøílohy',
    'oznámení pøi odstranìní pøílohy',
    'povinný',
    'Odlo¾eno',
    'Do dne',
    'Výchozí hodnota',
    'zapnuto',
    'vypnuto',
    'Metriky',
    /* 1180 */
    'Otevøené záznamy',
    'Vytvoøené v. Uzavøené',
    'týden',
    'èíslo',
    'Kopírovat',
    'Záznam je kopií "%1".',
    'Odhlásit',
    'oznámení pøi kopírování záznamu',
    'Nastavení',
    'Øádkù na stránku',
    /* 1190 */
    'Zálo¾ek na stránku',
    'Uzamknout',
    'Odemknout',
    'Typ skupiny',
    'globální',
    'místní',
    'Konfigurace',
    'Místní cesta',
    'URL',
    'Zabezpeèení',
    /* 1200 */
    'Minimální délka hesla',
    'Maximální poèet pokusù o pøihlá¹ení',
    'Doba uzamèení (min)',
    'Databáze',
    'Typ databáze',
    'Oracle',
    'Mysql',
    'Microsoft SQL Server',
    'Databázový server',
    'Název databáze',
    /* 1210 */
    'U¾ivatel',
    'Active Directory',
    'LDAP server',
    'Èíslo portu',
    'Úèet pro vyhledávání',
    'Základní DN',
    'Administrátoøi',
    'Upozornìní e-mailem',
    'Maximální velikost',
    'Ladìní',
    /* 1220 */
    'Re¾im ladìní',
    'povoleno (bez soukromých data)',
    'povoleno (v¹echna data)',
    'Ladící soubory',
    'Povoleno',
    'Zakázáno',
    '%1 min',
    'oprávnìní zobrazit záznamy',
    'Vybrat v¹e',
    'Autor',
    /* 1230 */
    'datum',
    'doba trvání',
    'Zobrazit pouze odlo¾ené',
    'Jméno pøedplatného',
    'Události',
    'Verze %1',
    'role',
    'Pøihlásit se',
    'Odhlásit se',
    'Upomínky',
    /* 1240 */
    'Název upomínky',
    'Pøedmìt upomínky',
    'Seznam pøíjemcù',
    'Nová pøipomínka (krok %1/%2)',
    'Pøipomínka "%1"',
    'oprávnìní zasílat pøipomínky',
    'Odeslat',
    'Nový filtr',
    'Filtr "%1"',
    'Nové pøedplatné',
    /* 1250 */
    'Pøedplatné "%1"',
    'Va¹e heslo LDAP',
    'Odkaz na jiný záznam lze vlo¾it zadáním "rec #" a jeho èíslo (napø. "rec # 305 ").',
    'Zobrazit pouze pøesunuté do stavu ...',
    'Sdílet s ...',
    'Exportovat',
    'Odebírat ostatní ...',
    'Pøihlá¹en',
    '%1 byl pøihlá¹en k záznamu.',
    '%1 byl odhlá¹en.',
    /* 1260 */
    'Kopie',
    'Úlo¾i¹tì',
    'LDAP atribut',
    'Pohledy',
    'Informace o pohledu',
    'Jméno pohledu',
    'Nový pohled (krok %1/%2)',
    'Pohled "%1"',
    'Výchozí pohled',
    'Nastavit',
    /* 1270 */
    'Sloupce',
    'Informace o sloupci',
    'Záhlaví sloupce',
    'Nový sloupec',
    'Sloupec "%1"',
    'Zarovnání',
    'doleva',
    'na støed',
    'doprava',
    'Slu¾ba bude nedostupná od %1 a¾ %2 (%3)',
    /* 1280 */
    'V¹echny pøidìlené mnì',
    'V¹echny vytvoøené mnou',
    'Odznaèit v¹e',
    'm/d/yyyy',
    'Výpis',
    'Podøízené záznamy',
    'Vytvoøit podøízený záznam',
    'Pøipojit podøízený záznam',
    'Odstranit podøízený záznam',
    'Èislo podøízeného záznamu',
    /* 1290 */
    'Podøízený záznam "%1" byl pøidán.',
    'Podøízený záznam "%1" byl odstranìn.',
    'oprávnìní pøidat podøízený záznam',
    'oprávnìní odstranit podøízený záznam',
    'oznámení pøi vytvo¾ení podøízeného záznamu',
    'oznámení pøi zru¹ení podøízeného záznamu',
    'vytvoøené záznamy',
    'uzavøené záznamy',
    'Dùvìrné',
    'Pøidat dùvìrný komentáø',
    /* 1300 */
    'oprávnìní pøidat / èíst dùvìrný komentáø',
    'Dùvìrný komentáø byl pøidán.',
    'Nadøízený záznam',
    'závislosti',
    'skrytý',
    'Pøidat oddìlovaè',
    'Oddìlovaè CSV',
    'Kódování CSV',
    'Konce øádkù CSV',
    'Výsledky vyhledávání (nefiltrované)',
    /* 1310 */
    'Povolit filtry',
    'Zakázat filtry',
    'Aktuální sada filtrù',
    'Ulo¾it sadu filtrù',
    'Sady filtrù',
    'Název sady filtrù',
    'Sada filtrù "%1"',
    'Aktuální pohled',
    'Ulo¾it pohled',
    'Rozbalit v¹e',
    /* 1320 */
    'Sbalit v¹e',
    'Obnovit výchozí,',
    'L/E',
    'PCRE pro kontrolu hodnot',
    'Vyhledávací PCRE pro transformaci hodnoty',
    'Nahrazovací PCRE pro transformaci hodnoty',
    'Výchozí následující stav',
    'Stav odlo¾ení',
    'zobrazit v¹e',
    'zobrazit pouze aktivní',
    /* 1330 */
    'Událost',
    'Prázdná sada filtrù',
    'Anonymní pøístup',
    '®ádné.',
    'Globální skupiny',
    'Náv¹tìvník',
    'Importovat',
    'oprávnìní smazat záznam',
    'Typ autentizace',
    'Výchozí jazyk',
    /* 1340 */
    'Platnost hesla (ve dnech)',
    'Platnost sezení (min)',
    'Výèet LDAP',
    'PostgreSQL',
    'seznam indexù',
    'seznam hodnot',
    'Vytvoøený',
    'Oznaèit jako pøeètené',
    'Registrovaný',
    'TLS',
    /* 1350 */
    'Komprese',
    'L/S',
    'Komentáøe',
);

?>
