<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2008-2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in French.
 *
 * @package Engine
 * @subpackage Localization
 * @author Philippe Infarnet
 */

$resource_french = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Tous les champs marqués comme requis doivent être remplis.',
    'La valeur par défaut doit être comprise entre %1 et %2.',
    'Le compte est desactivé.',
    'Le compte est verrouillé.',
    'Nom utilisateur invalide.',
    'Il existe déjà un compte portant ce nom.',
    'Adresse email invalide.',
    'Les mots de passe ne correspondent pas.',
    'Le mot de passe doit comporter au moins %1 caracteres.',
    'Il existe déjà un projet portant ce nom.',
    /* 210 */
    'Il existe déjà un groupe portant ce nom.',
    'Il existe déjà un modèle ou un préfixe portant ce nom.',
    'Il existe déjà un état portant ce nom ou abréviation.',
    'Il existe déjà un champ portant ce nom.',
    'Valeur entière incorecte.',
    'Une valeur entière doit être comprise entre %1 et %2.',
    'La valeur de "%1" doit être comprise entre %2 et %3.',
    'Le maximum doit être superieur au minimum.',
    'Le fichier chargé dépasse la taille définie par "upload_max_filesize" dans "php.ini".',
    'La taille de fichier chargé ne doit pas dépasser %1 Kbytes.',
    /* 220 */
    'Le fichier a été chargé en partie seulement.',
    'Aucun fichier chargé.',
    'Il manque un répertoire temporaire.',
    'Il existe déjà une pièce jointe portant ce nom.',
    'Enregistrement non trouvé.',
    'Il existe déjà un filtre portant ce nom.',
    'Date invalide.',
    'Une date doit être comprise entre %1 et %2.',
    'Heure invalide.',
    'Une heure doit être comprise entre %1 et %2.',
    /* 230 */
    'Il existe déjà une souscription portant ce nom.',
    'Il existe déjà une note de rappel portant ce nom.',
    'Note de rappel envoyée correctement.',
    'Il existe déjà une vue portant ce nom..',
    NULL,
    'Ecriture vers le disque défectueuse.',
    'Chargement du fichier interrompu par extension.',
    'Le JavaScript doit être activé.',
    'Message généré automatiquement, merci de ne pas y repondre.',
    NULL,
    /* 240 */
    NULL,
    'Une vue ne peut comporter plus de %1 colonnes.',
    'Format de la valeur "%1" erroné.',
    'Utilisateur non habilité.',
    'Utilisateur inconnu ou mauvais mot de passe.',
    'Erreur inconnue.',
    'Erreur du parseur XML.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Etes-vous sur de vouloir effacer toutes les vues selectionnées?',
    'Etes-vous sur de vouloir effacer ce compte?',
    'Etes-vous sur de vouloir effacer ce projet?',
    'Etes-vous sur de vouloir effacer ce groupe?',
    'Etes-vous sur de vouloir effacer ce modèle?',
    'Etes-vous sur de vouloir effacer cet état?',
    'Etes-vous sur de vouloir effacer ce champ?',
    NULL,
    'Etes-vous sur de vouloir reprendre cet enregistrement?',
    'Etes-vous sur de vouloir affecter cet enregistrement?',
    /* 310 */
    'Etes-vous sur de vouloir effacer tous les filtres selectionnés?',
    'Etes-vous sur de vouloir effacer toutes les souscriptions selectionnées?',
    'Etes-vous sur de vouloir envoyer cette note de rappel?',
    'Etes-vous sur de vouloir effacer cette note de  rappel?',
    'Etes-vous sur de vouloir quitter?',
    'Etes-vous sur de vouloir effacer cet enregistrement?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Français',
    'Se connecter',
    'OK',
    'Annuler',
    'Sauver',
    'Précédent',
    'Suivant',
    'Créer',
    'Modifier',
    'Effacer',
    /* 1010 */
    'Enregistrements',
    'Comptes',
    'Projets',
    'Changer le mot de passe',
    'Champs de l\'état "%1"',
    'aucun',
    'Total:',
    'Thème',
    'Information sur le compte',
    'Utilisateur',
    /* 1020 */
    'Nom complet',
    'Email',
    'Par défaut',
    'administrateur',
    'utilisateur',
    'Description',
    'Mot de passe',
    'Confirmation',
    'désactivé',
    'verrouillé',
    /* 1030 */
    'Nouveau compte',
    'Compte "%1"',
    'Information sur le projet',
    'Nom du projet',
    'Début',
    'Suspendu',
    'Nouveau projet',
    'Projet "%1"',
    'Groupes',
    'Information sur le groupe',
    /* 1040 */
    'Nom du groupe',
    'Nouveau groupe',
    'Groupe "%1"',
    'Appartenance',
    'Autres',
    'Membres',
    'Modèles',
    'Information sur le modèle',
    'Nom du modèle',
    'Préfixe',
    /* 1050 */
    'Nouveau modèle',
    'Modèle "%1"',
    'Etats',
    'Information sur l\'état',
    'Nom de l\'état',
    'Abréviation',
    'Type de l\'état',
    'initial',
    'intermédiaire',
    'final',
    /* 1060 */
    'Responsable',
    'rester inchangé',
    'affecter',
    'enlever',
    'Nouvel état',
    'Etat "%1"',
    'Créer en intermédiaire',
    'Créer en final',
    'Transitions',
    'Permissions',
    /* 1070 */
    'Rendre initial',
    'Autoriser',
    'Champs',
    'Information sur le champ',
    'Ordre',
    'Nom du champ',
    'Type du champ',
    'nombre',
    'chaîne',
    'texte multiligne',
    /* 1080 */
    'Requis',
    'oui',
    'non',
    'Minimum',
    'Maximum',
    'Longueur maxi',
    'requis',
    'Nouveau champ (étape %1/%2)',
    'Champ "%1"',
    'lecture seule',
    /* 1090 */
    'lecture et écriture',
    'Information générale',
    'ID',
    'Projet',
    'Modèle',
    'Etat',
    'Age',
    'Nouvel enregistrement',
    'Enregistrement "%1"',
    'Mes enregistrements',
    /* 1100 */
    'Historique',
    'Ajourner',
    'Reprendre',
    'Affecter',
    'Changer l\'état',
    'Timestamp',
    'Origine',
    'Enregistrement créé en état "%1".',
    'Enregistrement affecté le %1.',
    'Enregistrement modifié.',
    /* 1110 */
    'Etat changé en "%1".',
    'Enregistrement ajourné au %1.',
    'Enregistrement repris.',
    'Fichier "%1" attaché.',
    'Fichier "%1" enlevé.',
    'permission de créer des enregistrements',
    'permission de modifier des enregistrements',
    'permission d\'ajourner des enregistrements',
    'permission de reprendre des enregistrements',
    'permission d\'affecter des enregistrements',
    /* 1120 */
    'permission de changer l\'état d\'enregistrements affectes',
    'permission de joindre des fichiers',
    'permission d\'enlever des fichiers',
    'Langue',
    'Ajouter un commentaire',
    'Commentaire ajoute.',
    'permission d\'ajouter des commentaires',
    'Commentaire',
    'Joindre un fichier',
    'Enlever un fichier',
    /* 1130 */
    'Pièce jointe',
    'Nom de la pièce',
    'Fichier joint',
    'Pièces jointes',
    'Pas de champs.',
    'Age critique',
    'Inacitvité (gel)',
    'Changements',
    'Ancienne valeur',
    'Nouvelle valeur',
    /* 1140 */
    'case à cocher',
    'enregistrement',
    'liste',
    'éléments de liste',
    '%1 Kb',
    'Filtres',
    'Nom du filtre',
    'Projets',
    'Modèles',
    'Etats',
    /* 1150 */
    'Voir un enregistrement',
    'Seulement ceux créés par ...',
    'Seulement ceux affectés le ...',
    'Seulement ceux non-cloturés',
    'Sujet',
    'Recherche',
    'Paramètres',
    'Résultats',
    'Texte recherché',
    'Rechercher dans les champs',
    /* 1160 */
    'Rechercher dans les commentaires',
    'Statut',
    'actif',
    'Souscriptions',
    'signaler quand un enregistrement est créé',
    'signaler quand un enregistrement est affecté',
    'signaler quand un enregistrement est modifié',
    'signaler quand un enregistrement est changé',
    'signaler quand un enregistrement est ajourné',
    'signaler quand un enregistrement est repris',
    /* 1170 */
    'signaler quand un commentaire est ajouté',
    'signaler quand un fichier est joint',
    'signaler quand un fichier est enlevé',
    'requis',
    'Ajourné',
    'Echéance',
    'Valeur par défaut',
    'on',
    'off',
    'Mesures',
    /* 1180 */
    'Enregistrements en cours',
    'Creation vs Clôture',
    'semaine',
    'nombre',
    'Dupliquer',
    'Duplication de "%1".',
    'Se déconnecter',
    'signaler quand un enregistrement est dupliqué',
    'Paramètres',
    'Lignes par page',
    /* 1190 */
    'Signets par page',
    'Verrouller',
    'Déverrouiller',
    'Type de groupe',
    'global',
    'local',
    'Configuration',
    'Chemin racine local',
    'Chemin racine Web',
    'Securité',
    /* 1200 */
    'Longueur minimale du mot de passe',
    'Nombre maximal de tentatives de login',
    'Délai de verrouillage (min)',
    'Base de données',
    'Type de base de données',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Serveur de données',
    'Nom de la base',
    /* 1210 */
    'Utilisateur Database',
    'Active Directory',
    'Serveur LDAP',
    'Numéro de port',
    'Recherche du compte',
    'Base DN',
    'Administrateurs',
    'Notifications par Email',
    'Taille maximale',
    'Debug',
    /* 1220 */
    'Debug mode',
    'activé (sans les donnees privees)',
    'activé (toutes les donnees)',
    'Debug logs',
    'Activés',
    'Désactivés',
    NULL,
    'permission de voir les enregistrements seulement',
    'Tout sélectionner',
    'Auteur',
    /* 1230 */
    'date',
    'duree',
    'seulement les ajournés',
    'Nom de souscription',
    'Evénements',
    'Version %1',
    'rôle',
    'Souscrire',
    'Désinscrire',
    'Rappels',
    /* 1240 */
    'Nom du rappel',
    'Sujet du rappel',
    'Destinataires du rappel',
    'Nouveau rappel',
    'Note de rappel "%1"',
    'permission d\'envoyer aux destinataires',
    'Envoyer',
    'Nouveau filtre',
    'Filtre "%1"',
    'Nouvelle souscription',
    /* 1250 */
    'Souscription "%1"',
    NULL,
    'Vous pouver relier avec un autre entregistrement en précisant "rec#" et sa référence (ex. "rec#305").',
    'Seulement ceux dans l\'état ...',
    'Partager avec ...',
    'Exporter',
    'Souscrire d\'autres ...',
    'Souscrit',
    '%1 vous a inscrit dans l\'enregistrement.',
    '%1 est désinscrit.',
    /* 1260 */
    'Copie carbone',
    'Stockage',
    'Attributs LDAP',
    'Vues',
    NULL,
    'Nom de la vue',
    'Nouvelle vue',
    'Vue "%1"',
    'Pas de vues',
    'Définir',
    /* 1270 */
    'Colonnes',
    NULL,
    NULL,
    NULL,
    NULL,
    'Alignement',
    'gauche',
    'centre',
    'droite',
    'Service indisponible de %1 à %2 (%3)',
    /* 1280 */
    'Tous ceux qui me sont affectés',
    'Tous ceux que j\'ai créés',
    NULL,
    'm/j/aaaa',
    'Dump',
    'Subrecords',
    'Créer un subrecord',
    'Joindre un subrecord',
    'Enlever un subrecord',
    'ID du subrecord',
    /* 1290 */
    'Subrecord "%1" ajoute.',
    'Subrecord "%1" enleve.',
    'permission de joindre des subrecords',
    'permission de retirer des subrecords',
    'signaler quand un subrecord est ajouté',
    'signaler quand un subrecord est enlevé',
    'enregistrements existants',
    'enregistrements cloturés',
    'Confidentiel',
    'Ajouter un commentaire confidentiel',
    /* 1300 */
    'permission de lire/ajouter des commentaires confidentiels',
    'Un comentaire confidentiel a été ajouté.',
    'ID du parent',
    'dépendances',
    NULL,
    'Ajouter un séparateur',
    'Délimiteur CSV',
    'Codage CSV',
    'Fins de ligne CSV',
    NULL,
    /* 1310 */
    'Activer les filtres',
    'Désactiver les filtres',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Tout déplier',
    /* 1320 */
    'Tout replier',
    NULL,
    'D/Ev',
    'PCRE pour contrôler les champs',
    'PCRE recherché pour transformer les champs',
    'PCRE remplacé pour transformer les champs',
    'Etat suivant par défaut',
    'Ajournements',
    'Montrer tous',
    'Seulement les actifs',
    /* 1330 */
    'Evénement',
    NULL,
    'Accès invité',
    'Aucun.',
    'Global groupes',
    'Invité',
    'Importer',
    'permission de supprimer des enregistrements',
    NULL,
    'Langue par défaut',
    /* 1340 */
    'Expiration du mot de passe (jours)',
    'Expiration de la session (min)',
    'Enumeration LDAP',
    'PostgreSQL',
    'liste de nombres',
    'liste de chaînes',
    'Cree le',
    'Marquer comme lu',
    'Inscrit',
    'TLS',
    /* 1350 */
    'Compression',
    'D/Et',
    'Commentaires',
    'Taille',
    'Apparence',
    'CSV',
    'Activer',
    'Désactiver',
    'Visualiser',
    'Propriétaire',
    /* 1360 */
    'Tout le monde.',
    'Marquer Non-lu',
    'Enregistrement parent',
);

?>
