<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2008-2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Indonesian.
 *
 * @package Engine
 * @subpackage Localization
 * @author Febrina H. Ariendhita
 */

$resource_indonesian = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Semua ruas yang ditandai harus diisi.',
    'Nilai standar harus berada di antara %1 sampai %2.',
    'Akun dinonaktifkan.',
    'Akun dikunci.',
    'Nama pengguna tidak valid.',
    'Akun dengan nama pengguna yang dimasukkan telah ada.',
    'Email tidak valid.',
    'Kata sandi tidak cocok.',
    'Kata sandi minimal %1 karakter.',
    'Proyek dengan nama yang dimasukkan telah ada.',
    /* 210 */
    'Kelompok dengan nama yang dimasukkan telah ada.',
    'Templat dengan nama atau prefiks yang dimasukkan telah ada.',
    'Status dengan nama atau singkatan yang dimasukkan telah ada.',
    'Ruas dengan nama yang dimasukkan telah ada.',
    'Nilai bilangan bulat tidak valid.',
    'Nilai bilangan bulat harus berada di antara %1 sampai %2.',
    'Nilai "%1" harus berada di antara %2 sampai %3.',
    'Nilai maksimum harus lebih besar dari nilai minimum.',
    'Berkas yang diunggah melebihi "upload_max_filesize" dalam "php.ini".',
    'Ukuran berkas yang diunggah tidak boleh lebih besar dari %1 Kbita.',
    /* 220 */
    'Berkas yang diunggah hanya diunggah sebagian.',
    'Tidak ada berkas yang diunggah.',
    'Satu folder sementara hilang.',
    'Lampiran dengan nama yang dimasukkan telah ada.',
    'Data tidak ditemukan.',
    'Filter dengan nama yang dimasukkan telah ada.',
    'Nilai tanggal tidak valid.',
    'Nilai tanggal harus berada di antara %1 sampai %2.',
    'Nilai waktu tidak valid.',
    'Nilai waktu harus berada di antara %1 sampai %2.',
    /* 230 */
    'Pendaftaran dengan nama yang dimasukkan telah ada.',
    'Pengingat dengan nama yang dimasukkan telah ada.',
    'Pengingat berhasil dikirim.',
    'Tampilan dengan nama yang dimasukkan telah ada.',
    NULL,
    'Gagal menulis berkas ke disk.',
    'Pengunggahan berkas dihentikan oleh ekstensi.',
    'JavaScript harus diaktifkan.',
    'Ini adalah pesan otomatis, jangan dibalas.',
    NULL,
    /* 240 */
    NULL,
    'Tampilan tidak boleh lebih dari %1 kolom.',
    'Nilai "%1" tidak lolos cek format.',
    'Pengguna tidak berwenang.',
    'Nama pengguna tidak dikenal atau kata sandi salah.',
    'Jenis pengesahan tidak dikenal.',
    'Kesalahan yang tidak diketahui.',
    'Kesalahan XML parser.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Anda yakin ingin menghapus semua tampilan yang dipilih?',
    'Anda yakin ingin menghapus akun ini?',
    'Anda yakin ingin menghapus proyek ini?',
    'Anda yakin ingin menghapus kelompok ini?',
    'Anda yakin ingin menghapus templat ini?',
    'Anda yakin ingin menghapus status ini?',
    'Anda yakin ingin menghapus ruas ini?',
    NULL,
    'Anda yakin ingin melanjutkan data ini?',
    'Anda yakin ingin menugaskan data ini?',
    /* 310 */
    'Anda yakin ingin menghapus semua filter yang dipilih?',
    'Anda yakin ingin menghapus semua pendaftaran yang dipilih?',
    'Anda yakin ingin mengirim pengingat ini?',
    'Anda yakin ingin menghapus pengingat ini?',
    'Anda yakin ingin keluar?',
    'Anda yakin ingin menghapus data ini?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Bahasa Indonesia',
    'Masuk log',
    'OK',
    'Batal',
    'Simpan',
    'Kembali',
    'Berikutnya',
    'Buat',
    'Ubah',
    'Hapus',
    /* 1010 */
    'Data',
    'Akun',
    'Proyek',
    'Ubah kata sandi',
    'Ruas status "%1"',
    'tidak ada',
    'Total:',
    NULL,
    'Informasi akun',
    'Nama pengguna',
    /* 1020 */
    'Nama lengkap',
    'E-mail',
    NULL,
    'administrator',
    'pengguna',
    'Deskripsi',
    'Kata sandi',
    'Konfirmasi',
    'dinonaktifkan',
    'dikunci',
    /* 1030 */
    'Akun baru',
    'Akun "%1"',
    'Informasi proyek',
    'Nama proyek',
    'Waktu mulai',
    'ditangguhkan',
    'Proyek baru',
    'Proyek "%1"',
    'Kelompok',
    'Informasi kelompok',
    /* 1040 */
    'Nama kelompok',
    'Kelompok baru',
    'Kelompok "%1"',
    'Keanggotaan',
    'Lain-lain',
    'Anggota',
    'Templat',
    'Informasi templat',
    'Nama templat',
    'Prefiks',
    /* 1050 */
    'Templat baru',
    'Templat "%1"',
    'Status',
    'Informasi status',
    'Nama status',
    'Singkatan',
    'Jenis status',
    'bagian awal',
    'bagian tengah',
    'bagian akhir',
    /* 1060 */
    'Tanggung jawab',
    'tetap tidak diubah',
    'tugaskan',
    'hapus',
    'Status baru',
    'Status "%1"',
    'Buat bagian tengah',
    'Buat bagian akhir',
    'Transisi',
    'Izin',
    /* 1070 */
    'Buat bagian awal',
    'Diizinkan',
    'Ruas',
    'Informasi ruas',
    'Urutan',
    'Nama ruas',
    'Tipe ruas',
    'jumlah',
    'string',
    'teks multibaris',
    /* 1080 */
    'Diperlukan',
    'ya',
    'tidak',
    'Nilai minimal',
    'Nilai maksimal',
    'Panjang maksimal',
    'diperlukan',
    'Ruas baru (langkah %1/%2)',
    'Ruas "%1"',
    'hanya-baca',
    /* 1090 */
    'baca dan tulis',
    'Informasi umum',
    'ID',
    'Proyek',
    'Templat',
    'Status',
    'Masa',
    'Data baru (langkah %1/%2)',
    'Data "%1"',
    NULL,
    /* 1100 */
    'Sejarah',
    'Tunda',
    'Lanjutkan',
    'Tugaskan',
    'Ubah status',
    'Tanda waktu',
    'Pembuat',
    'Data dibuat di dalam status "%1".',
    'Data ditugaskan di %1.',
    'Data dimodifikasi.',
    /* 1110 */
    'Status diubah ke "%1".',
    'Data ditunda hingga %1.',
    'Data dilanjutkan.',
    'Berkas "%1" dilampirkan.',
    'Berkas "%1" dipindahkan.',
    'izin untuk membuat data',
    'izin untuk memodifikasi data',
    'izin untuk menunda data',
    'izin untuk melanjutkan data',
    'izin untuk menugaskan kembali data yang ditugaskan',
    /* 1120 */
    'izin untuk mengubah status dari data yang ditugaskan',
    'izin untuk melampirkan berkas',
    'izin untuk menghapus berkas',
    'Bahasa',
    'Tambahkan komentar',
    'Komentar ditambahkan.',
    'izin untuk menambahkan komentar',
    'Komentar',
    'Lampirkan berkas',
    'Hapus berkas',
    /* 1130 */
    'Lampiran',
    'Nama lampiran',
    'Berkas lampiran',
    'Lampiran',
    'Tidak ada ruas.',
    'Masa kritis',
    'Waktu dibekukan',
    'Perubahan',
    'Nilai lama',
    'Nilai baru',
    /* 1140 */
    'kotak cek',
    'data',
    'daftar',
    'Butir daftar',
    '%1 Kb',
    'Filter',
    'Nama filter',
    'Semua proyek',
    'Semua templat',
    'Semua status',
    /* 1150 */
    'Lihat data',
    'Tampilkan hanya yang dibuat oleh ...',
    'Tampilkan hanya yang ditugaskan di ...',
    'tampilkan hanya yang belum ditutup',
    'Subjek',
    'Cari',
    'Parameter pencarian',
    'Hasil pencarian',
    'Teks yang akan dicari',
    'cari di ruas',
    /* 1160 */
    'cari di komentar',
    'Status',
    'aktif',
    'Pendaftaran',
    'beritahu saat data dibuat',
    'beritahu saat data ditugaskan',
    'beritahu saat data dimodifikasi',
    'beritahu saat status berubah',
    'beritahu saat data ditunda',
    'beritahu saat data dilanjutkan',
    /* 1170 */
    'beritahu saat komentar ditambahkan',
    'beritahu saat berkas dilampirkan',
    'beritahu saat berkas dipindahkan',
    'diperlukan',
    'Ditunda',
    'Tanggal jatuh tempo',
    'Nilai standar',
    'aktif',
    'tidak aktif',
    'Metrik',
    /* 1180 */
    'Data yang dibuka',
    'Pembuatan >< Hasil Akhir',
    'minggu',
    'jumlah',
    'Klon',
    'Data adalah klon dari "%1".',
    'Keluar log',
    'beritahu saat data diklon',
    'Pengaturan',
    'Baris per halaman',
    /* 1190 */
    'Marka buku per halaman',
    'Kunci',
    'Buka kunci',
    'Jenis kelompok',
    'global',
    'lokal',
    'Konfigurasi',
    'Alur akar lokal',
    'Alur akar web',
    'Keamanan',
    /* 1200 */
    'Panjang kata sandi minimum',
    'Jumlah maksimum percobaan login',
    'Waktu penguncian (menit)',
    'Basis data',
    'Jenis basis data',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Server basis data',
    'Nama basis data',
    /* 1210 */
    'Pengguna basis data',
    'Direktori Aktif',
    'Server LDAP',
    'Nomor port',
    'Cari akun',
    'Basis DN',
    'Administrator',
    'Pemberitahuan email',
    'Ukuran maksimum',
    'Debug',
    /* 1220 */
    'Mode debug',
    'diaktifkan (tanpa data pribadi)',
    'diaktifkan (semua data)',
    'Catatan debug',
    'Diaktifkan',
    'Dinonaktifkan',
    '%1 menit',
    'izin untuk melihat data saja',
    'Pilih semua',
    'Penulis',
    /* 1230 */
    'tanggal',
    'durasi',
    'tunjukkan yang ditunda saja',
    'Nama pendaftaran',
    'Peristiwa',
    'Versi %1',
    'peran',
    'Daftar',
    'Batalkan pendaftaran',
    'Pengingat',
    /* 1240 */
    'Nama pengingat',
    'Subjek pengingat',
    'Penerima pengingat',
    'Pengingat baru (langkah %1/%2)',
    'Pengingat "%1"',
    'izin untuk mengirimkan pengingat',
    'Kirim',
    'Filter baru',
    'Filter "%1"',
    'Pendaftaran baru',
    /* 1250 */
    'Pendaftaran "%1"',
    'Kata sandi LDAP Anda',
    'Anda dapat menyisipkan tautan ke data lain dengan menentukan "rec#" dan nomornya (contoh: "rec#305").',
    'Tampilkan hanya yang dipindahkan ke status ...',
    'Berbagi dengan ...',
    'Ekspor',
    'Daftarkan yang lain ...',
    'Terdaftar',
    '%1 mendaftarkan Anda kepada data.',
    '%1 membatalkan pendaftaran.',
    /* 1260 */
    'Kopi karbon',
    'Penyimpanan',
    'Atribut LDAP',
    'Tampilan',
    'Informasi tampilan',
    'Nama tampilan',
    'Tampilan baru',
    'Tampilan "%1"',
    'Tidak ada tampilan',
    'Tetapkan',
    /* 1270 */
    'Kolom',
    NULL,
    NULL,
    NULL,
    NULL,
    'Perataan',
    'kiri',
    'tengah',
    'kanan',
    'Layanan akan tidak tersedia sejak %1 hingga %2 (%3)',
    /* 1280 */
    'Semua yang ditugaskan pada saya',
    'Semua yang dibuat oleh saya',
    'Batalkan semua pilihan',
    'm/d/yyyy',
    'Timbunan',
    'Subdata',
    'Buat subdata',
    'Lampirkan subdata',
    'Hapus subdata',
    'ID subdata',
    /* 1290 */
    'Subdata "%1" ditambahkan.',
    'Subdata "%1" dihapus.',
    'izin untuk menambahkan subdata',
    'izin untuk menghapus subdata',
    'beritahu saat subdata ditambahkan',
    'beritahu saat subdata dihapus',
    'data yang dibuat',
    'data yang ditutup',
    'Rahasia',
    'Tambahkan komentar rahasia',
    /* 1300 */
    'izin untuk menambahkan/membaca komentar rahasia',
    'Komentar rahasia ditambahkan.',
    'ID induk',
    'keterpautan',
    NULL,
    'Tambahkan pemisah',
    'Pembatas CSV',
    'Penyandian CSV',
    'Akhiran baris CSV',
    NULL,
    /* 1310 */
    'Aktifkan filter',
    'Nonaktifkan filter',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Perbesar semua',
    /* 1320 */
    'Perkecil semua',
    NULL,
    'T/P',
    'PCRE untuk memeriksa nilai ruas',
    'Cari PCRE untuk mengubah nilai ruas',
    'Ganti PCRE untuk mengubah nilai ruas',
    'Status berikutnya secara standar',
    'Status penundaan',
    'tampilkan semua',
    'tampilkan yang aktif saja',
    /* 1330 */
    'Peristiwa',
    NULL,
    'Akses pengguna tamu.',
    'Tidak ada.',
    'Global kelompok',
    'Tamu',
    'Impor',
    'izin untuk menghapus data',
    'Jenis pengesahan',
    'Bahasa standar',
    /* 1340 */
    'Waktu kadaluarsa kata sandi (hari)',
    'Waktu kadaluarsa sesi (menit)',
    'Penghitungan LDAP',
    'PostgreSQL',
    'daftar nomor',
    'daftar string',
    'Dibuat',
    'Tandai telah dibaca',
    'Terdaftar',
    'TLS',
    /* 1350 */
    'Kompresi',
    'T/S',
    'Komentar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    /* 1360 */
    NULL,
    NULL,
    NULL,
);

?>
