<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2006-2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Latvian.
 * All the prompts are in ISO-8859-13 encoding.
 *
 * @package Engine
 * @subpackage Localization
 * @author Janis Kruminsch
 */

$resource_latvian = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Jâaizpilda visi lauciòi, kas atzîmçti kâ obligâtie.',
    'Noklusçjuma nozîmei jàbût no %1 lîdz %2 apgabalâ.',
    'Lietotâja konts ir atslçgts.',
    'Lietotâja konts ir bloíçts.',
    'Nezinâms lietotâja vârds.',
    'Lietotâja konts ar tâdu lietotâja vârdu jau eksistç.',
    'Nepareiza e-pasta adrese.',
    'Paroles nesakrît.',
    'Parolei jâsatur vismaz %1 simbolu.',
    'Projekts ar tâdu nosaukumu jau eksistç.',
    /* 210 */
    'Grupa ar tâdu nosaukumu jau eksistç.',
    'Lekâls ar tâdu nosaukumu vai priedçkli jau eksistç.',
    'Stâvoklis ar tâdu nosaukumu vai saîsinâjumu jau eksistç.',
    'Atribûts ar tâdu nosaukumu jau eksistç.',
    'Nekorekts veselais skaitlis.',
    'Veselajam skaitlim jâbût no %1 lîdz %2 apgabalâ.',
    '"%1" lauciòa lielumam jâbût no %2 lîdz %3 apgabalâ.',
    'Maksimâlajam lielumam jâbût lielâkam par minimâlo.',
    'Augðupielâdçjamâ faila izmçrs ir lielâks nekâ "upload_max_filesize" direktîvâ norâdîtais "php.ini" failâ.',
    'Augðupielâdçjamâ faila izmçrs nevar bût lielâks par %1 Kbaitiem.',
    /* 220 */
    'Augðupielâdçjamais fails tika augðupielâdçts tikai daïçji.',
    'Fails netika augðupielâdçts.',
    'Nav atrasta laicîgâ mape.',
    'Pielikums ar tâdu vârdu jau eksistç.',
    'Ieraksts nav atrasts.',
    'Filtrs ar ievadîto nosaukumu jau eksistç.',
    'Nepareizs datums.',
    'Datuma nozîmei jâbût %1 lîdz %2 apgabalâ.',
    'Nepareizs laiks.',
    'Laika nozîmei jâbût %1 lîdz %2 apgabalâ.',
    /* 230 */
    'Parakstîðanâs ar ievadîto nosaukumu jau eksistç.',
    'Atgâdinâjums ar tâdu vârdu jau eksistç.',
    'Atgâdinâjums tika veiksmîgi nosûtîts.',
    'Skats ar tàdu nosaukumu jau eksistç.',
    'Stabiñð ar tâdu nosaukumu jau eksistç.',
    'Diska ieraksta kïûda',
    'Paplaðinàjums apstàdinàja faila ielàdi',
    'JavaScript jâbût ieslçgtam.',
    'Ðî ir automâtiskâ ziòa, lûdzu, neatbildiet uz to, jûsu atbilde netiks saòemta.',
    'Norâdîtais bçrnieraksts jau eksistç.',
    /* 240 */
    'Filtru kopa ar tâdu nosaukumu jau eksistç.',
    'Skatîjumam nevar bût vairâk nekâ %1 stabiòu.',
    '"%1" vçrtîbas formâta pârbaudes kïûme.',
    'Lietotâjs nav autorizçts.',
    'Nezinâms lietotâja vârds vai parole.',
    'Nezinâms autorizâcijas tips.',
    'Nezinâma kïûda.',
    'XML-parsçtâja kïûda.',
    'Datubâzes savienojuma kïûda.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Vai tieðâm dzçst visus skatîjumus?',
    'Vai tieðâm vçlaties dzçst ðo kontu?',
    'Vai tieðâm vçlaties dzçst ðo projektu?',
    'Vai tieðâm vçlaties dzçst ðo grupu?',
    'Vai tieðâm vçlaties dzçst ðo lekâlu?',
    'Vai tieðâm vçlaties dzçst ðo stâvokli?',
    'Vai tieðâm vçlaties dzçst ðo atribûtu?',
    'Vai tieðâm vçlaties atlikt ðo ierakstu?',
    'Vai tieðâm vçlaties atsâkt ðo ierakstu?',
    'Vai tieðâm vçlaties atzîmçt ðo ierakstu?',
    /* 310 */
    'Vai tieðâm vçlaties dzçst visus atzîmçtos filtrus?',
    'Vai tieðâm vçlaties dzçst visas atzîmçtâs parakstîðanâs?',
    'Vai tieðâm nosûtît ðo atgâdinâjumu?',
    'Vai tieðâm dzçst ðo atgâdinâjumu?',
    'Vai tieðâm vçlaties dzçst ðo stabiòu?',
    'Vai tieðâm vçlaties iziet?',
    'Vai esat pârliecinâti, ka vçlaties dzçst visas filtru kopas?',
    'Tieðâm vçlaties dzçst ðo ierakstu?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Latvieðu',
    'Ieiet',
    'Labi',
    'Atcelt',
    'Saglabât',
    'Atpakaï',
    'Tâlâk',
    'Izveidot',
    'Mainît',
    'Dzçst',
    /* 1010 */
    'Ieraksti',
    'Lietotâji',
    'Projekti',
    'Mainît paroli',
    '"%1" stâvokïa atribûti',
    'nav',
    'Kopâ:',
    NULL,
    'Konta informâcija',
    'Lietotâja vârds',
    /* 1020 */
    'Pilns vârds',
    'E-pasts',
    NULL,
    'administrators',
    'lietotâjs',
    'Apraksts',
    'Parole',
    'Apstiprinâjums',
    'atslçgts',
    'bloíçts',
    /* 1030 */
    'Jauns lietotâjs',
    'Konts "%1"',
    'Projekta informâcija',
    'Projekta nosaukums',
    'Sâkuma laiks',
    'atlikts',
    'Jauns projekts',
    'Projekts "%1"',
    'Grupas',
    'Grupas informâcija',
    /* 1040 */
    'Grupas nosaukums',
    'Jauna grupa',
    'Grupa "%1"',
    'Dalîba',
    'Pârçjie',
    'Dalîbnieki',
    'Lekâli',
    'Lekâla informâcija',
    'Lekâla nosaukums',
    'Priedçklis',
    /* 1050 */
    'Jauns lekâls',
    'Lekâls "%1"',
    'Stâvokïi',
    'Stâvokïa informâcija',
    'Stâvokïa nosaukums',
    'Saîsinâjums',
    'Stâvokïa tips',
    'sâkotnçjs',
    'vidus',
    'beigu',
    /* 1060 */
    'Atbildîgais',
    'atstât neizmainîtu',
    'adresçt',
    'noòemt',
    'Jauns stâvoklis',
    'Stâvoklis "%1"',
    'Izveidot vidus',
    'Izveidot gala',
    'Pârejas',
    'Tiesîbas',
    /* 1070 */
    'Padarît par sâkotnçju',
    'Atïauti',
    'Atribûti',
    'Atribûta informâcija',
    'Kârtîba',
    'Atribûta nosaukums',
    'Atribûta tips',
    'skaitlis',
    'rinda',
    'daudzrindu teksts',
    /* 1080 */
    'Obligâts',
    'Jâ',
    'Nç',
    'Min.lielums',
    'Max.lielums',
    'Max.garums',
    'obligâts',
    'Jauns atribûts (solis %1/%2)',
    'Atribûts "%1"',
    'tikai nolasîðanai',
    /* 1090 */
    'lasît un rakstît',
    'Pamatinformâcija',
    'ID',
    'Projekts',
    'Lekâls',
    'Stâvoklis',
    'Vecums',
    'Jauns ieraksts (solis %1/%2)',
    'Ieraksts "%1"',
    'Pâriet',
    /* 1100 */
    'Vçsture',
    'Atlikt',
    'Atsâkt',
    'Adresçt',
    'Mainît stâvokli',
    'Laiks',
    'Izveidotâjs',
    'Ieraksts ir izveidots "%1" stâvoklî',
    'Ieraksts adresçts uz %1.',
    'Ieraksts ir mainîts',
    /* 1110 */
    'Stâvoklis ir mainîts uz "%1"',
    'Ieraksts ir atlikts lîdz "%1"',
    'Ieraksts ir atsâkts',
    'Fails "%1" tika pievienots',
    'Fails "%1" tika dzçsts',
    'tiesîbas izveidot ierakstus',
    'tiesîbas mainît ierakstus',
    'tiesîbas atlikt ierakstus',
    'tiesîbas atsâkt ierakstus',
    'tiesîbas pâradresçt adresçtos ierakstus',
    /* 1120 */
    'tiesîbas mainît adresçto ierakstu stâvokli',
    'tiesîbas pievienot failus',
    'tiesîbas dzçst failus',
    'Valoda',
    'Pievienot komentâru',
    'Komentârs tika pievienots.',
    'tiesîbas pievienot komentârus',
    'Komentârs',
    'Pievienot failu',
    'Dzçst failu',
    /* 1130 */
    'Pielikums',
    'Pielikuma nosaukums',
    'Pielikuma fails',
    'Pielikumi',
    'Nav atribûtu.',
    'Kritisks vecums',
    'Atlikðanas laiks',
    'Izmaiòas',
    'Vecâ nozîme',
    'Jaunâ nozîme',
    /* 1140 */
    'atlases ðûna',
    'ieraksts',
    'saraksts',
    'Saraksta elementi',
    '%1 Kb',
    'Filtri',
    'Filtra nosaukums',
    'Visi projekti',
    'Visi lekâli',
    'Visi stâvokïi',
    /* 1150 */
    'Skatîties ierakstu',
    'Râdît tikai tos, kurus izveidoja ...',
    'Râdît tikai tos, kuri adresçti ...',
    'râdît tikai neaizvçrtos',
    'Temats',
    'Meklçðana',
    'Meklçðanas parametri',
    'Meklçðanas rezultâti',
    'Meklçjamais teksts',
    'meklçt atribûtos',
    /* 1160 */
    'meklçt komentâros',
    'Statuss',
    'aktîvs',
    'Parakstîðanâs',
    'ziòot par ieraksta izveidoðanu',
    'ziòot par ieraksta adresçðanu',
    'ziòot par ieraksta izmainîðanos',
    'ziòot par ieraksta stâvokïa izmainîðanos',
    'ziòot par ieraksta atlkðanu',
    'ziòot par ieraksta atsâkðanu',
    /* 1170 */
    'ziòot par komentâra pievienoðanu',
    'ziòot par faila pievienoðanu',
    'ziòot par faila dzçðanu',
    'obligâts',
    'Atlikts',
    'Lîdz datumam',
    'Noklusçjuma nozîme',
    'iesl.',
    'izsl.',
    'Mçrîjumi',
    /* 1180 */
    'Atvçrtie ieraksti',
    'Izveidoðana un aizvçrðana',
    'nedçïa',
    'daudzums',
    'Klonçt',
    'Ieraksts klonçts no "%1".',
    'Iziet',
    'ziòot par ieraksta klonçðanu',
    'Iestatîjumi',
    'Ierakstu lapâ',
    /* 1190 */
    'Grâmatzîmju lapâ',
    'Bloíçt',
    'Atbloíçt',
    'Grupas tips',
    'globâlâ',
    'lokâlâ',
    'Konfigurâcija',
    'Lokâlais pamatceïð',
    'PamatURL',
    'Droðîba',
    /* 1200 */
    'Minimâlais paroles garums',
    'Maksimâlais ielogoðanâs mçìinâjumu skaits',
    'Bloíçðanas taimauts (min)',
    'Datubâze',
    'Datubâzes tips',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Servera vârds',
    'Datubâzes nosaukums',
    /* 1210 */
    'Datubâzes lietotâjs',
    'Active Directory',
    'LDAP serveris',
    'Porta numurs',
    'Meklçðanas konts',
    'Bâzes mape',
    'Administratori',
    'E-pasta ziòojumi',
    'Maksimâlais izmçrs',
    'Kïûdu meklçðana',
    /* 1220 */
    'Kïûdu meklçðanas reþîms',
    'ieslçgts (pez privâtdatiem)',
    'iezlçgts (visi dati)',
    'Kïûdu meklçðanas þurnâli',
    'Ieslçgts',
    'Izslçgts',
    '%1 min',
    'tiesîbas tikai skatîties ierakstus',
    'Atlasît visu',
    'Autors',
    /* 1230 */
    'datums',
    'ilgums',
    'râdît tikai atliktos',
    'Parakstîðanâs nosaukums',
    'Notikumi',
    'Versija %1',
    'loma',
    'Parakstîties',
    'Atrakstîties',
    'Atgâdinâjumi',
    /* 1240 */
    'Atgâdinâjuma vârds',
    'Atgâdinâjuma temats',
    'Atgâdinâjuma saòçmçji',
    'Jauns atgâdinâjums (solis %1 no %2) ',
    'Atgâdinâjums "%1"',
    'tiesîbas sûtît atgâdinâjumus',
    'Nosûtît',
    'Jauns filtrs',
    'Filtrs "%1"',
    'Jauna parakstîðanâs',
    /* 1250 */
    'Parakstîðanâs "%1"',
    'Jûsu LDAP parole',
    'Jûs varat ievietot saiti uz citu ierakstu, norâdot "rec#" un tâ numuru (piem. "rec#305").',
    'Râdît tikai tos, kas pârvietoti stâvokïos ...',
    'Koplietoðana ar ...',
    'Eksportçðana',
    'Parakstît citus...',
    'Parakstîtie',
    '%1 parakstîja Jûs uz ierakstu.',
    '%1 atrakstîjâs.',
    /* 1260 */
    'Kopija',
    'Krâtuve',
    'LDAP-atribûts',
    'Skati',
    'Skata informâcija',
    'Skata nosaukums',
    'Jauns skats (solis %1/%2)',
    'Skats "%1"',
    'Bez skata',
    'Noteikt',
    /* 1270 */
    'Stabiòi',
    'Stabiòu informâcija',
    'Stabiòa virsraksts',
    'Jauns stabiòð',
    'Stabiòâ "%1"',
    'Izlîdzinàt',
    'pa kreisi',
    'centrâ',
    'pa labi',
    'Pakalpojums nebûs pieejams no %1 lïdz %2 (%3)',
    /* 1280 */
    'Visi, kas adresçti uz mani',
    'Manis izveidotie',
    'Novâkt atlasi',
    'gggg.mm.dd.',
    'Izmete',
    'Pçcteèi',
    'Izveidot pçcteci',
    'Pievienot pçcteci',
    'Novâkt pçcteci',
    'Pçcteèa ID',
    /* 1290 */
    'Pievienots "%1" pçctecis.',
    'Novâkts ¥%1¡ pçctecis.',
    'tiesîbas pievienot pçcteèus',
    'tiesîbas novâkt pçcteèus',
    'ziòot kad tiek pievienots pçctecis',
    'ziòot kad tiek novâkts pçctecis',
    'izveidotie ieraksti',
    'slçgtie ieraksti',
    'Konfidenciâls',
    'Pievienot konfidenciâlu komentâru',
    /* 1300 */
    'tiesîbas pievienot/lasît konfidenciâlos komentârus',
    'Tika pievienots konfidenciâls komentârs.',
    'Pirmsteèa ID',
    'atkarîba',
    'slçpts',
    'Pievienot atdalîtâju',
    'CSV Norobeþotâjs',
    'CSV kodçðana',
    'CSV rindu nobeigumi',
    'Meklçðanas rezultâti (nefiltrçti)',
    /* 1310 */
    'Ieslçgt filtrus',
    'Izslçgt filtrus',
    'Aktuâlâ filtru kopa',
    'Saglabât filtru kopu',
    'Filtru kopas',
    'Filtru kopas nosaukums',
    '"%1" filtru kopa',
    'Aktuâlais skatîjums',
    'Saglabât skatîjumu',
    'Izvçrst visu',
    /* 1320 */
    'Savçrst visu',
    'Atiestatît uz noklusçjumu',
    'P/N',
    'PCRE lauku vçrtîbu pârbaudei',
    'Meklçt PCRE lauku vçrtîbu mainîðanai',
    'Pârvietot PCRE lauku vçrtîbu mainîðana',
    'Nâkoðais stâvoklis pçc noklusçjuma',
    'Atlikðanas statuss',
    'râdît visu',
    'râdît tikai aktîvos',
    /* 1330 */
    'Notikums',
    'Nav filtru kopas',
    'Viesu piekïuve',
    'Nav.',
    'Globâlâ grupas',
    'Viesis',
    'Imports',
    'tiesîbas dzçst ierakstus',
    'Autorizâcias tips',
    'Noklusçjuma valoda',
    /* 1340 */
    'Paroles derîguma termiòð (d.)',
    'Sesijas derîguma termiòð (min.)',
    'LDAP pârskaitîjums',
    'PostgreSQL',
    'indeksu saraksts',
    'vçrtîbu saraksts',
    'Izveidots',
    'Atzîmçt kâ izlasîtos',
    'Reìistrçta',
    'TLS',
    /* 1350 */
    'Kompresija',
    'P/S',
    'Komentâri',
    'Izmçrs',
    'Izskats',
    'CSV',
    'Ieslçgt',
    'Izslçgt',
    'Priekðskats',
    'Saimnieks',
    /* 1360 */
    'Ikviens.',
    'Atzîmçt kâ neizlasîtu',
    'Vecâkieraksti',
);

?>
