<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2006-2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Latvian.
 *
 * @package Engine
 * @subpackage Localization
 * @author Janis Kruminsch
 */

$resource_latvian = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Jāaizpilda visi lauciņi, kas atzīmēti kā obligātie.',
    'Noklusējuma nozīmei jąbūt no %1 līdz %2 apgabalā.',
    'Lietotāja konts ir atslēgts.',
    'Lietotāja konts ir bloķēts.',
    'Nezināms lietotāja vārds.',
    'Lietotāja konts ar tādu lietotāja vārdu jau eksistē.',
    'Nepareiza e-pasta adrese.',
    'Paroles nesakrīt.',
    'Parolei jāsatur vismaz %1 simbolu.',
    'Projekts ar tādu nosaukumu jau eksistē.',
    /* 210 */
    'Grupa ar tādu nosaukumu jau eksistē.',
    'Lekāls ar tādu nosaukumu vai priedēkli jau eksistē.',
    'Stāvoklis ar tādu nosaukumu vai saīsinājumu jau eksistē.',
    'Atribūts ar tādu nosaukumu jau eksistē.',
    'Nekorekts veselais skaitlis.',
    'Veselajam skaitlim jābūt no %1 līdz %2 apgabalā.',
    '"%1" lauciņa lielumam jābūt no %2 līdz %3 apgabalā.',
    'Maksimālajam lielumam jābūt lielākam par minimālo.',
    'Augšupielādējamā faila izmērs ir lielāks nekā "upload_max_filesize" direktīvā norādītais "php.ini" failā.',
    'Augšupielādējamā faila izmērs nevar būt lielāks par %1 Kbaitiem.',
    /* 220 */
    'Augšupielādējamais fails tika augšupielādēts tikai daļēji.',
    'Fails netika augšupielādēts.',
    'Nav atrasta laicīgā mape.',
    'Pielikums ar tādu vārdu jau eksistē.',
    'Ieraksts nav atrasts.',
    'Filtrs ar ievadīto nosaukumu jau eksistē.',
    'Nepareizs datums.',
    'Datuma nozīmei jābūt %1 līdz %2 apgabalā.',
    'Nepareizs laiks.',
    'Laika nozīmei jābūt %1 līdz %2 apgabalā.',
    /* 230 */
    'Parakstīšanās ar ievadīto nosaukumu jau eksistē.',
    'Atgādinājums ar tādu vārdu jau eksistē.',
    'Atgādinājums tika veiksmīgi nosūtīts.',
    'Skats ar tądu nosaukumu jau eksistē.',
    'Lūdzu norādiet šī ieraksta īsu aprakstu.',
    'Diska ieraksta kļūda',
    'Paplašinąjums apstądinąja faila ielądi',
    'JavaScript jābūt ieslēgtam.',
    'Šī ir automātiskā ziņa, lūdzu, neatbildiet uz to, jūsu atbilde netiks saņemta.',
    'Nederīga decimālvērtība.',
    /* 240 */
    'Decimālvērtībai ir jābūt no %1 līdz %2.',
    'Skatījumam nevar būt vairāk nekā %1 stabiņu.',
    '"%1" vērtības formāta pārbaudes kļūme.',
    'Lietotājs nav autorizēts.',
    'Nezināms lietotāja vārds vai parole.',
    'Nezināma kļūda.',
    'XML-parsētāja kļūda.',
    NULL,

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Vai tiešām dzēst visus skatījumus?',
    'Vai tiešām vēlaties dzēst šo kontu?',
    'Vai tiešām vēlaties dzēst šo projektu?',
    'Vai tiešām vēlaties dzēst šo grupu?',
    'Vai tiešām vēlaties dzēst šo lekālu?',
    'Vai tiešām vēlaties dzēst šo stāvokli?',
    'Vai tiešām vēlaties dzēst šo atribūtu?',
    'Vai jūs tiešām vēlaties mainīt šī ieraksta stāvokli?',
    'Vai tiešām vēlaties atsākt šo ierakstu?',
    'Vai tiešām vēlaties atzīmēt šo ierakstu?',
    /* 310 */
    'Vai tiešām vēlaties dzēst visus atzīmētos filtrus?',
    'Vai tiešām vēlaties dzēst visas atzīmētās parakstīšanās?',
    'Vai tiešām nosūtīt šo atgādinājumu?',
    'Vai tiešām dzēst šo atgādinājumu?',
    'Vai tiešām vēlaties iziet?',
    'Tiešām vēlaties dzēst šo ierakstu?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Latviešu',
    'Ieiet',
    'Labi',
    'Atcelt',
    'Saglabāt',
    'Atpakaļ',
    'Tālāk',
    'Izveidot',
    'Mainīt',
    'Dzēst',
    /* 1010 */
    'Ieraksti',
    'Lietotāji',
    'Projekti',
    'Mainīt paroli',
    '"%1" stāvokļa atribūti',
    'nav',
    'Kopā:',
    'Motīvs',
    'Konta informācija',
    'Lietotāja vārds',
    /* 1020 */
    'Pilns vārds',
    'E-pasts',
    'Noklusējuma',
    'administrators',
    'lietotājs',
    'Apraksts',
    'Parole',
    'Apstiprinājums',
    'atslēgts',
    'bloķēts',
    /* 1030 */
    'Jauns lietotājs',
    'Konts "%1"',
    'Projekta informācija',
    'Projekta nosaukums',
    'Sākuma laiks',
    'atlikts',
    'Jauns projekts',
    'Projekts "%1"',
    'Grupas',
    'Grupas informācija',
    /* 1040 */
    'Grupas nosaukums',
    'Jauna grupa',
    'Grupa "%1"',
    'Dalība',
    'Pārējie',
    'Dalībnieki',
    'Lekāli',
    'Lekāla informācija',
    'Lekāla nosaukums',
    'Priedēklis',
    /* 1050 */
    'Jauns lekāls',
    'Lekāls "%1"',
    'Stāvokļi',
    'Stāvokļa informācija',
    'Stāvokļa nosaukums',
    'Saīsinājums',
    'Stāvokļa tips',
    'sākotnējs',
    'vidus',
    'beigu',
    /* 1060 */
    'Atbildīgais',
    'atstāt neizmainītu',
    'adresēt',
    'noņemt',
    'Jauns stāvoklis',
    'Stāvoklis "%1"',
    'Izveidot vidus',
    'Izveidot gala',
    'Pārejas',
    'Tiesības',
    /* 1070 */
    'Padarīt par sākotnēju',
    'Atļauti',
    'Atribūti',
    'Atribūta informācija',
    'Kārtība',
    'Atribūta nosaukums',
    'Atribūta tips',
    'skaitlis',
    'rinda',
    'daudzrindu teksts',
    /* 1080 */
    'Obligāts',
    'Jā',
    'Nē',
    'Min.lielums',
    'Max.lielums',
    'Max.garums',
    'obligāts',
    'Jauns atribūts (solis %1/%2)',
    'Atribūts "%1"',
    'tikai nolasīšanai',
    /* 1090 */
    'lasīt un rakstīt',
    'Pamatinformācija',
    'ID',
    'Projekts',
    'Lekāls',
    'Stāvoklis',
    'Vecums',
    'Jauns ieraksts',
    'Ieraksts "%1"',
    'Mani ieraksti',
    /* 1100 */
    'Vēsture',
    'Atlikt',
    'Atsākt',
    'Adresēt',
    'Mainīt stāvokli',
    'Laiks',
    'Izveidotājs',
    'Ieraksts ir izveidots "%1" stāvoklī',
    'Ieraksts adresēts uz %1.',
    'Ieraksts ir mainīts',
    /* 1110 */
    'Stāvoklis ir mainīts uz "%1"',
    'Ieraksts ir atlikts līdz "%1"',
    'Ieraksts ir atsākts',
    'Fails "%1" tika pievienots',
    'Fails "%1" tika dzēsts',
    'tiesības izveidot ierakstus',
    'tiesības mainīt ierakstus',
    'tiesības atlikt ierakstus',
    'tiesības atsākt ierakstus',
    'tiesības pāradresēt adresētos ierakstus',
    /* 1120 */
    'tiesības atvērt ierakstus no jauna',
    'tiesības pievienot failus',
    'tiesības dzēst failus',
    'Valoda',
    'Pievienot komentāru',
    'Komentārs tika pievienots.',
    'tiesības pievienot komentārus',
    'Komentārs',
    'Pievienot failu',
    'Dzēst failu',
    /* 1130 */
    'Pielikums',
    'Pielikuma nosaukums',
    'Pielikuma fails',
    'Pielikumi',
    'Nav atribūtu.',
    'Kritisks vecums',
    'Atlikšanas laiks',
    'Izmaiņas',
    'Vecā nozīme',
    'Jaunā nozīme',
    /* 1140 */
    'atlases šūna',
    'ieraksts',
    'saraksts',
    'Saraksta elementi',
    '%1 Kb',
    'Filtri',
    'Filtra nosaukums',
    'Visi projekti',
    'Visi lekāli',
    'Visi stāvokļi',
    /* 1150 */
    'Skatīties ierakstu',
    'Rādīt tikai tos, kurus izveidoja ...',
    'Rādīt tikai tos, kuri adresēti ...',
    'rādīt tikai neaizvērtos',
    'Temats',
    'Meklēšana',
    'Meklēšanas parametri',
    'Meklēšanas rezultāti',
    'Meklējamais teksts',
    'meklēt atribūtos',
    /* 1160 */
    'meklēt komentāros',
    'Statuss',
    'aktīvs',
    'Parakstīšanās',
    'ziņot par ieraksta izveidošanu',
    'ziņot par ieraksta adresēšanu',
    'ziņot par ieraksta izmainīšanos',
    'ziņot par ieraksta stāvokļa izmainīšanos',
    'ziņot par ieraksta atlkšanu',
    'ziņot par ieraksta atsākšanu',
    /* 1170 */
    'ziņot par komentāra pievienošanu',
    'ziņot par faila pievienošanu',
    'ziņot par faila dzēšanu',
    'obligāts',
    'Atlikts',
    'Līdz datumam',
    'Noklusējuma nozīme',
    'iesl.',
    'izsl.',
    'Mērījumi',
    /* 1180 */
    'Atvērtie ieraksti',
    'Izveidošana un aizvēršana',
    'nedēļa',
    'daudzums',
    'Klonēt',
    'Ieraksts klonēts no "%1".',
    'Iziet',
    'ziņot par ieraksta klonēšanu',
    'Iestatījumi',
    'Ierakstu lapā',
    /* 1190 */
    'Grāmatzīmju lapā',
    'Bloķēt',
    'Atbloķēt',
    'Grupas tips',
    'globālā',
    'lokālā',
    'Konfigurācija',
    'Rinda',
    'PamatURL',
    'Drošība',
    /* 1200 */
    'Minimālais paroles garums',
    'Maksimālais ielogošanās mēģinājumu skaits',
    'Bloķēšanas taimauts (min)',
    'Datubāze',
    'Datubāzes tips',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Servera vārds',
    'Datubāzes nosaukums',
    /* 1210 */
    'Datubāzes lietotājs',
    'Active Directory',
    'LDAP serveris',
    'Porta numurs',
    'Meklēšanas konts',
    'Bāzes mape',
    'Administratori',
    'E-pasta ziņojumi',
    'Maksimālais izmērs',
    'Kļūdu meklēšana',
    /* 1220 */
    'Kļūdu meklēšanas režīms',
    'ieslēgts (pez privātdatiem)',
    'iezlēgts (visi dati)',
    'Kļūdu meklēšanas žurnāli',
    'Ieslēgts',
    'Izslēgts',
    'decimāls',
    'tiesības tikai skatīties ierakstus',
    'Atlasīt visu',
    'Autors',
    /* 1230 */
    'datums',
    'ilgums',
    'rādīt tikai atliktos',
    'Parakstīšanās nosaukums',
    'Notikumi',
    'Versija %1',
    'loma',
    'Parakstīties',
    'Atrakstīties',
    'Atgādinājumi',
    /* 1240 */
    'Atgādinājuma vārds',
    'Atgādinājuma temats',
    'Atgādinājuma saņēmēji',
    'Jauns atgādinājums',
    'Atgādinājums "%1"',
    'tiesības sūtīt atgādinājumus',
    'Nosūtīt',
    'Jauns filtrs',
    'Filtrs "%1"',
    'Jauna parakstīšanās',
    /* 1250 */
    'Parakstīšanās "%1"',
    'Rindu skaits daudzrindu ierakstos',
    'Jūs varat ievietot saiti uz citu ierakstu, norādot "rec#" un tā numuru (piem. "rec#305").',
    'Rādīt tikai tos, kas pārvietoti stāvokļos ...',
    'Koplietošana ar ...',
    'Eksportēšana',
    'Parakstīt citus...',
    'Parakstītie',
    '%1 parakstīja Jūs uz ierakstu.',
    '%1 atrakstījās.',
    /* 1260 */
    'Kopija',
    'Krātuve',
    'LDAP-atribūts',
    'Skati',
    'Aizvērt',
    'Skata nosaukums',
    'Jauns skats',
    'Skats "%1"',
    'Bez skata',
    'Noteikt',
    /* 1270 */
    'Stabiņi',
    'Brīdinājums',
    'Informācija',
    'Kļūda',
    'Jautājums',
    'Izlīdzinąt',
    'pa kreisi',
    'centrā',
    'pa labi',
    'Pakalpojums nebūs pieejams no %1 lļdz %2 (%3)',
    /* 1280 */
    'Visi, kas adresēti uz mani',
    'Manis izveidotie',
    'Rādīt e-pastos',
    'Lūdzu uzgaidiet…',
    'Izmete',
    'Pēcteči',
    'Izveidot pēcteci',
    'Pievienot pēcteci',
    'Novākt pēcteci',
    'Autoatjaunošanas laika intervāls',
    /* 1290 */
    'Pievienots "%1" pēctecis.',
    'Novākts „%1” pēctecis.',
    'tiesības pievienot pēctečus',
    'tiesības novākt pēctečus',
    'ziņot kad tiek pievienots pēctecis',
    'ziņot kad tiek novākts pēctecis',
    'izveidotie ieraksti',
    'slēgtie ieraksti',
    'Konfidenciāls',
    'Pievienot konfidenciālu komentāru',
    /* 1300 */
    'tiesības pievienot/lasīt konfidenciālos komentārus',
    'Tika pievienots konfidenciāls komentārs.',
    'Pirmsteča ID',
    'atkarība',
    'Laika zona',
    'Pievienot atdalītāju',
    'CSV Norobežotājs',
    'CSV kodēšana',
    'CSV rindu nobeigumi',
    'Paziņot ja ieraksts tiek atvērts no jauna.',
    /* 1310 */
    'Ieslēgt filtrus',
    'Izslēgt filtrus',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Izvērst visu',
    /* 1320 */
    'Savērst visu',
    'Ieraksts tika atvērts no jauna “%1” stāvoklī.',
    'P/N',
    'PCRE lauku vērtību pārbaudei',
    'Meklēt PCRE lauku vērtību mainīšanai',
    'Pārvietot PCRE lauku vērtību mainīšana',
    'Nākošais stāvoklis pēc noklusējuma',
    'Atlikšanas statuss',
    'rādīt visu',
    'rādīt tikai aktīvos',
    /* 1330 */
    'Notikums',
    'Atvērt no jauna',
    'Viesu piekļuve',
    'Nav.',
    'Globālā grupas',
    'Viesis',
    'Imports',
    'tiesības dzēst ierakstus',
    NULL,
    'Noklusējuma valoda',
    /* 1340 */
    'Paroles derīguma termiņš (d.)',
    'Sesijas derīguma termiņš (min.)',
    'LDAP pārskaitījums',
    'PostgreSQL',
    'indeksu saraksts',
    'vērtību saraksts',
    'Izveidots',
    'Atzīmēt kā izlasītos',
    'Reģistrēta',
    'TLS',
    /* 1350 */
    'Kompresija',
    'P/S',
    'Komentāri',
    'Izmērs',
    'Izskats',
    'CSV',
    'Ieslēgt',
    'Izslēgt',
    'Priekšskats',
    'Saimnieks',
    /* 1360 */
    'Ikviens.',
    'Atzīmēt kā neizlasītu',
    'Vecākieraksti',
);

?>
