<?php

/**
 * Localization
 *
 * This module contains prompts translated in Latvian.
 * All the prompts are in ISO-8859-13 encoding.
 *
 * @package Engine
 * @subpackage Localization
 * @author Janis Kruminsch
 */

//--------------------------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system.
//  Copyright (C) 2006-2009 by Artem Rodygin
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//--------------------------------------------------------------------------------------------------
//  Author                  Date            Description of modifications
//--------------------------------------------------------------------------------------------------
//  Janis Kruminsch         2006-05-16      new-258: Latvian localization.
//  Janis Kruminsch         2006-05-16      new-005: Oracle support.
//  Janis Kruminsch         2006-06-19      new-236: Single record subscription.
//  Janis Kruminsch         2006-06-25      new-222: Email reminders.
//  Janis Kruminsch         2006-06-28      new-272: When reminder is sent a notification should be displayed to user.
//  Janis Kruminsch         2006-06-28      new-274: "Crumbs" for creation and modification of filters or subscriptions are not clear.
//  Janis Kruminsch         2006-07-24      bug-201: 'Access Forbidden' error with cyrillic named attachments.
//  Janis Kruminsch         2006-08-07      bug-300: Cannot login with Active Directory credentials.
//  Janis Kruminsch         2006-08-13      new-305: Note with explanation of links to other records should be added where needed.
//  Artem Rodygin           2006-08-20      new-313: Implement HTTP authentication.
//  Janis Kruminsch         2006-10-14      new-137: Custom queries.
//  Janis Kruminsch         2006-10-17      new-361: Extended custom queries.
//  Janis Kruminsch         2006-11-04      new-364: Default fields values.
//  Janis Kruminsch         2006-11-05      new-365: Filters sharing.
//  Janis Kruminsch         2006-11-07      new-366: Export to CSV.
//  Janis Kruminsch         2006-11-12      new-368: User should be able to subscribe other persons.
//  Artem Rodygin           2006-11-15      bug-381: Attachments of some types are not opened in valid applications.
//  Janis Kruminsch         2006-11-15      new-374: Carbon copies in subscriptions.
//  Janis Kruminsch         2006-11-18      bug-388: "Configuration" page does not display path where binary attachments are stored.
//  Janis Kruminsch         2006-11-18      bug-389: Motorola LDAP server returns "Insufficient rights" error.
//  Janis Kruminsch         2006-11-20      new-377: Custom views.
//  Janis Kruminsch         2006-12-04      new-405: Default filter for new user.
//  Janis Kruminsch         2006-12-10      new-432: Maintenance notice banner.
//  Janis Kruminsch         2006-12-14      new-446: Add processing of new upload errors.
//  Janis Kruminsch         2006-12-17      new-457: Default filter for new user.
//  Janis Kruminsch         2006-12-20      new-459: 'Filters' and 'Subscriptions' pages should contain ability to clear current selection.
//  Artem Rodygin           2006-12-22      new-462: Postpone date should be displayed as separate field.
//  Janis Kruminsch         2006-12-23      new-463: Date field names should be extended with date format explanation.
//  Janis Kruminsch         2006-12-26      bug-467: Latvian prompts should be reviewed.
//  Artem Rodygin           2006-12-27      bug-470: State permissions must not be used when record is being created.
//  Artem Rodygin           2006-12-27      new-472: User must have ability to log out.
//  Janis Kruminsch         2006-12-28      new-474: Rename field permissions to make them more clear.
//  Artem Rodygin           2006-12-30      new-475: Turning subscriptions on and off is not clear.
//  Janis Kruminsch         2007-01-15      new-483: JavaScript ability notice.
//  Janis Kruminsch         2007-04-03      new-512: Banner about 'no reply on autogenerated message' for notifications.
//  Janis Kruminsch         2007-04-03      new-499: Records dump to text file.
//  Janis Kruminsch         2007-07-05      new-533: Links between records.
//  Janis Kruminsch         2007-07-16      new-545: Chart legend is required.
//  Janis Kruminsch         2007-07-16      new-546: Confidential comments.
//  Janis Kruminsch         2007-08-06      new-551: Rework dependencies into "parent-child" relations.
//  Artem Rodygin           2007-08-27      [rhonda] Hide author from 'Innovation' templates.
//  Janis Kruminsch         2007-09-09      new-563: Custom separators inside fields set.
//  Janis Kruminsch         2007-09-12      new-576: [SF1788286] Export to CSV
//  Janis Kruminsch         2007-09-13      new-566: Choose encoding for record dump and export of records list.
//  Janis Kruminsch         2007-10-02      new-513: Apply current filter set to search results.
//  Janis Kruminsch         2007-10-30      new-564: Filters set.
//  Artem Rodygin           2007-11-05      new-571: View should show all records of current filters set.
//  Janis Kruminsch         2007-11-06      new-562: Ability to show only last values of any state.
//  Janis Kruminsch         2007-11-11      bug-624: dbx_error(): Too many tables; MySQL can only use 61 tables in a join
//  Janis Kruminsch         2007-11-13      new-599: Separated "Age" in custom views.
//  Janis Kruminsch         2007-11-14      new-548: Custom links in text fields.
//  Yury Udovichenko        2007-11-19      new-623: Default state in states list.
//  Yury Udovichenko        2007-11-20      new-536: Ability to hide postpone records from the list.
//  Janis Kruminsch         2007-11-29      new-637: Subject of notifications should contain subject of records.
//  Janis Kruminsch         2007-11-29      new-617: Add 'no view' and 'no filter set' to related comboboxes.
//  Janis Kruminsch         2007-12-27      new-659: Set default language
//  Janis Kruminsch         2007-12-30      bug-660: [SF1860788] PHP4 html_entity_decode() is not working
//  Janis Kruminsch         2008-01-16      new-666: Buttons "Previous" & "Next" on record view page.
//  Janis Kruminsch         2008-01-28      new-531: LDAP Guest users
//  Janis Kruminsch         2008-01-31      new-601: [SF1814666] Export and Import Templates
//  Janis Kruminsch         2008-02-27      new-676: [SF1898731] Delete Issues from Workflow
//  Artem Rodygin           2008-02-28      new-294: PostgreSQL support.
//  Janis Kruminsch         2008-03-02      bug-681: Update configuration page with new options.
//  Janis Kruminsch         2008-04-30      bug-699: Views // Names of custom columns are duplicated in the list of available columns, when there are two fields of different types with the same name.
//  Janis Kruminsch         2008-05-01      new-715: Show creation time in the list of records.
//  Janis Kruminsch         2008-07-02      new-729: [SF2008579] Mark all records as read
//  Janis Kruminsch         2008-11-11      new-749: Guest access for unauthorized users.
//  Artem Rodygin           2009-01-08      new-774: 'Anyone' system role permissions.
//  Artem Rodygin           2009-04-12      bug-806: German translation causes two ambiguous "zuruck" buttons.
//  Artem Rodygin           2009-04-26      new-817: Field permissions dialog refactoring.
//  Artem Rodygin           2009-04-26      new-818: Change buttons layout on viewing record page.
//  Artem Rodygin           2009-10-12      new-848: LDAP TLS support.
//--------------------------------------------------------------------------------------------------

$resource_latvian = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Jâaizpilda visi lauciòi, kas atzîmçti kâ obligâtie.',
    'Noklusçjuma nozîmei jàbût no %1 lîdz %2 apgabalâ.',
    'Lietotâja konts ir atslçgts.',
    'Lietotâja konts ir bloíçts.',
    'Nezinâms lietotâja vârds.',
    'Lietotâja konts ar tâdu lietotâja vârdu jau eksistç.',
    'Nepareiza e-pasta adrese.',
    'Paroles nesakrît.',
    'Parolei jâsatur vismaz %1 simbolu.',
    'Projekts ar tâdu nosaukumu jau eksistç.',
    /* 210 */
    'Grupa ar tâdu nosaukumu jau eksistç.',
    'Lekâls ar tâdu nosaukumu vai priedçkli jau eksistç.',
    'Stâvoklis ar tâdu nosaukumu vai saîsinâjumu jau eksistç.',
    'Atribûts ar tâdu nosaukumu jau eksistç.',
    'Nekorekts veselais skaitlis.',
    'Veselajam skaitlim jâbût no %1 lîdz %2 apgabalâ.',
    '"%1" lauciòa lielumam jâbût no %2 lîdz %3 apgabalâ.',
    'Maksimâlajam lielumam jâbût lielâkam par minimâlo.',
    'Augðupielâdçjamâ faila izmçrs ir lielâks nekâ "upload_max_filesize" direktîvâ norâdîtais "php.ini" failâ.',
    'Augðupielâdçjamâ faila izmçrs nevar bût lielâks par %1 Kbaitiem.',
    /* 220 */
    'Augðupielâdçjamais fails tika augðupielâdçts tikai daïçji.',
    'Fails netika augðupielâdçts.',
    'Nav atrasta laicîgâ mape.',
    'Pielikums ar tâdu vârdu jau eksistç.',
    'Ieraksts nav atrasts.',
    'Filtrs ar ievadîto nosaukumu jau eksistç.',
    'Nepareizs datums.',
    'Datuma nozîmei jâbût %1 lîdz %2 apgabalâ.',
    'Nepareizs laiks.',
    'Laika nozîmei jâbût %1 lîdz %2 apgabalâ.',
    /* 230 */
    'Parakstîðanâs ar ievadîto nosaukumu jau eksistç.',
    'Atgâdinâjums ar tâdu vârdu jau eksistç.',
    'Atgâdinâjums tika veiksmîgi nosûtîts.',
    'Skats ar tàdu nosaukumu jau eksistç.',
    'Stabiñð ar tâdu nosaukumu jau eksistç.',
    'Diska ieraksta kïûda',
    'Paplaðinàjums apstàdinàja faila ielàdi',
    'JavaScript jâbût ieslçgtam.',
    'Ðî ir automâtiskâ ziòa, lûdzu, neatbildiet uz to, jûsu atbilde netiks saòemta.',
    'Norâdîtais bçrnieraksts jau eksistç.',
    /* 240 */
    'Filtru kopa ar tâdu nosaukumu jau eksistç.',
    'Skatîjumam nevar bût vairâk nekâ %1 stabiòu.',
    '"%1" vçrtîbas formâta pârbaudes kïûme.',
    'Lietotâjs nav autorizçts.',
    'Nezinâms lietotâja vârds vai parole.',
    'Nezinâms autorizâcijas tips.',
    'Nezinâma kïûda.',
    'XML-parsçtâja kïûda.',
    'Datubâzes savienojuma kïûda.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Vai tieðâm dzçst visus skatîjumus?',
    'Vai tieðâm vçlaties dzçst ðo kontu?',
    'Vai tieðâm vçlaties dzçst ðo projektu?',
    'Vai tieðâm vçlaties dzçst ðo grupu?',
    'Vai tieðâm vçlaties dzçst ðo lekâlu?',
    'Vai tieðâm vçlaties dzçst ðo stâvokli?',
    'Vai tieðâm vçlaties dzçst ðo atribûtu?',
    'Vai tieðâm vçlaties atlikt ðo ierakstu?',
    'Vai tieðâm vçlaties atsâkt ðo ierakstu?',
    'Vai tieðâm vçlaties atzîmçt ðo ierakstu?',
    /* 310 */
    'Vai tieðâm vçlaties dzçst visus atzîmçtos filtrus?',
    'Vai tieðâm vçlaties dzçst visas atzîmçtâs parakstîðanâs?',
    'Vai tieðâm nosûtît ðo atgâdinâjumu?',
    'Vai tieðâm dzçst ðo atgâdinâjumu?',
    'Vai tieðâm vçlaties dzçst ðo stabiòu?',
    'Vai tieðâm vçlaties iziet?',
    'Vai esat pârliecinâti, ka vçlaties dzçst visas filtru kopas?',
    'Tieðâm vçlaties dzçst ðo ierakstu?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Latvieðu',
    'Ieiet',
    'Labi',
    'Atcelt',
    'Saglabât',
    'Atpakaï',
    'Tâlâk',
    'Izveidot',
    'Mainît',
    'Dzçst',
    /* 1010 */
    'Ieraksti',
    'Lietotâji',
    'Projekti',
    'Mainît paroli',
    '"%1" stâvokïa atribûti',
    'nav',
    'Kopâ:',
    'saglabât paroli',
    'Konta informâcija',
    'Lietotâja vârds',
    /* 1020 */
    'Pilns vârds',
    'E-pasts',
    'Tiesîbas',
    'administrators',
    'lietotâjs',
    'Apraksts',
    'Parole',
    'Apstiprinâjums',
    'atslçgts',
    'bloíçts',
    /* 1030 */
    'Jauns lietotâjs',
    'Konts "%1"',
    'Projekta informâcija',
    'Projekta nosaukums',
    'Sâkuma laiks',
    'atlikts',
    'Jauns projekts',
    'Projekts "%1"',
    'Grupas',
    'Grupas informâcija',
    /* 1040 */
    'Grupas nosaukums',
    'Jauna grupa',
    'Grupa "%1"',
    'Dalîba',
    'Pârçjie',
    'Dalîbnieki',
    'Lekâli',
    'Lekâla informâcija',
    'Lekâla nosaukums',
    'Priedçklis',
    /* 1050 */
    'Jauns lekâls',
    'Lekâls "%1"',
    'Stâvokïi',
    'Stâvokïa informâcija',
    'Stâvokïa nosaukums',
    'Saîsinâjums',
    'Stâvokïa tips',
    'sâkotnçjs',
    'vidus',
    'beigu',
    /* 1060 */
    'Atbildîgais',
    'atstât neizmainîtu',
    'adresçt',
    'noòemt',
    'Jauns stâvoklis',
    'Stâvoklis "%1"',
    'Izveidot vidus',
    'Izveidot gala',
    'Pârejas',
    'Tiesîbas',
    /* 1070 */
    'Padarît par sâkotnçju',
    'Atïauti',
    'Atribûti',
    'Atribûta informâcija',
    'Kârtîba',
    'Atribûta nosaukums',
    'Atribûta tips',
    'skaitlis',
    'rinda',
    'daudzrindu teksts',
    /* 1080 */
    'Obligâts',
    'Jâ',
    'Nç',
    'Min.lielums',
    'Max.lielums',
    'Max.garums',
    'obligâts',
    'Jauns atribûts (solis %1/%2)',
    'Atribûts "%1"',
    'tikai nolasîðanai',
    /* 1090 */
    'lasît un rakstît',
    'Pamatinformâcija',
    'ID',
    'Projekts',
    'Lekâls',
    'Stâvoklis',
    'Vecums',
    'Jauns ieraksts (solis %1/%2)',
    'Ieraksts "%1"',
    'Pâriet',
    /* 1100 */
    'Vçsture',
    'Atlikt',
    'Atsâkt',
    'Adresçt',
    'Mainît stâvokli',
    'Laiks',
    'Izveidotâjs',
    'Ieraksts ir izveidots "%1" stâvoklî',
    'Ieraksts adresçts uz %1.',
    'Ieraksts ir mainîts',
    /* 1110 */
    'Stâvoklis ir mainîts uz "%1"',
    'Ieraksts ir atlikts lîdz "%1"',
    'Ieraksts ir atsâkts',
    'Fails "%1" tika pievienots',
    'Fails "%1" tika dzçsts',
    'tiesîbas izveidot ierakstus',
    'tiesîbas mainît ierakstus',
    'tiesîbas atlikt ierakstus',
    'tiesîbas atsâkt ierakstus',
    'tiesîbas pâradresçt adresçtos ierakstus',
    /* 1120 */
    'tiesîbas mainît adresçto ierakstu stâvokli',
    'tiesîbas pievienot failus',
    'tiesîbas dzçst failus',
    'Valoda',
    'Pievienot komentâru',
    'Komentârs tika pievienots.',
    'tiesîbas pievienot komentârus',
    'Komentârs',
    'Pievienot failu',
    'Dzçst failu',
    /* 1130 */
    'Pielikums',
    'Pielikuma nosaukums',
    'Pielikuma fails',
    'Pielikumi',
    'Nav atribûtu.',
    'Kritisks vecums',
    'Atlikðanas laiks',
    'Izmaiòas',
    'Vecâ nozîme',
    'Jaunâ nozîme',
    /* 1140 */
    'atlases ðûna',
    'ieraksts',
    'saraksts',
    'Saraksta elementi',
    '%1 Kb',
    'Filtri',
    'Filtra nosaukums',
    'Visi projekti',
    'Visi lekâli',
    'Visi stâvokïi',
    /* 1150 */
    'Skatîties ierakstu',
    'Râdît tikai tos, kurus izveidoja ...',
    'Râdît tikai tos, kuri adresçti ...',
    'râdît tikai neaizvçrtos',
    'Temats',
    'Meklçðana',
    'Meklçðanas parametri',
    'Meklçðanas rezultâti (filtrçti)',
    'Meklçjamais teksts',
    'meklçt atribûtos',
    /* 1160 */
    'meklçt komentâros',
    'Statuss',
    'aktîvs',
    'Parakstîðanâs',
    'ziòot par ieraksta izveidoðanu',
    'ziòot par ieraksta adresçðanu',
    'ziòot par ieraksta izmainîðanos',
    'ziòot par ieraksta stâvokïa izmainîðanos',
    'ziòot par ieraksta atlkðanu',
    'ziòot par ieraksta atsâkðanu',
    /* 1170 */
    'ziòot par komentâra pievienoðanu',
    'ziòot par faila pievienoðanu',
    'ziòot par faila dzçðanu',
    'obligâts',
    'Atlikts',
    'Lîdz datumam',
    'Noklusçjuma nozîme',
    'iesl.',
    'izsl.',
    'Mçrîjumi',
    /* 1180 */
    'Atvçrtie ieraksti',
    'Izveidoðana un aizvçrðana',
    'nedçïa',
    'daudzums',
    'Klonçt',
    'Ieraksts klonçts no "%1".',
    'Iziet',
    'ziòot par ieraksta klonçðanu',
    'Iestatîjumi',
    'Ierakstu lapâ',
    /* 1190 */
    'Grâmatzîmju lapâ',
    'Bloíçt',
    'Atbloíçt',
    'Grupas tips',
    'globâlâ',
    'lokâlâ',
    'Konfigurâcija',
    'Lokâlais pamatceïð',
    'PamatURL',
    'Droðîba',
    /* 1200 */
    'Minimâlais paroles garums',
    'Maksimâlais ielogoðanâs mçìinâjumu skaits',
    'Bloíçðanas taimauts (min)',
    'Datubâze',
    'Datubâzes tips',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Servera vârds',
    'Datubâzes nosaukums',
    /* 1210 */
    'Datubâzes lietotâjs',
    'Active Directory',
    'LDAP serveris',
    'Porta numurs',
    'Meklçðanas konts',
    'Bâzes mape',
    'Administratori',
    'E-pasta ziòojumi',
    'Maksimâlais izmçrs',
    'Kïûdu meklçðana',
    /* 1220 */
    'Kïûdu meklçðanas reþîms',
    'ieslçgts (pez privâtdatiem)',
    'iezlçgts (visi dati)',
    'Kïûdu meklçðanas þurnâli',
    'Ieslçgts',
    'Izslçgts',
    '%1 min',
    'tiesîbas tikai skatîties ierakstus',
    'Atlasît visu',
    'Autors',
    /* 1230 */
    'datums',
    'ilgums',
    'râdît tikai atliktos',
    'Parakstîðanâs nosaukums',
    'Notikumi',
    'Versija %1',
    'loma',
    'Parakstîties',
    'Atrakstîties',
    'Atgâdinâjumi',
    /* 1240 */
    'Atgâdinâjuma vârds',
    'Atgâdinâjuma temats',
    'Atgâdinâjuma saòçmçji',
    'Jauns atgâdinâjums (solis %1 no %2) ',
    'Atgâdinâjums "%1"',
    'tiesîbas sûtît atgâdinâjumus',
    'Nosûtît',
    'Jauns filtrs',
    'Filtrs "%1"',
    'Jauna parakstîðanâs',
    /* 1250 */
    'Parakstîðanâs "%1"',
    'Jûsu LDAP parole',
    'Jûs varat ievietot saiti uz citu ierakstu, norâdot "rec#" un tâ numuru (piem. "rec#305").',
    'Râdît tikai tos, kas pârvietoti stâvokïos ...',
    'Koplietoðana ar ...',
    'Eksportçðana',
    'Parakstît citus...',
    'Parakstîtie',
    '%1 parakstîja Jûs uz ierakstu.',
    '%1 atrakstîjâs.',
    /* 1260 */
    'Kopija',
    'Krâtuve',
    'LDAP-atribûts',
    'Skati',
    'Skata informâcija',
    'Skata nosaukums',
    'Jauns skats (solis %1/%2)',
    'Skats "%1"',
    'Bez skata',
    'Noteikt',
    /* 1270 */
    'Stabiòi',
    'Stabiòu informâcija',
    'Stabiòa virsraksts',
    'Jauns stabiòð',
    'Stabiòâ "%1"',
    'Izlîdzinàt',
    'pa kreisi',
    'centrâ',
    'pa labi',
    'Pakalpojums nebûs pieejams no %1 lïdz %2 (%3)',
    /* 1280 */
    'Visi, kas adresçti uz mani',
    'Manis izveidotie',
    'Novâkt atlasi',
    'gggg.mm.dd.',
    'Izmete',
    'Pçcteèi',
    'Izveidot pçcteci',
    'Pievienot pçcteci',
    'Novâkt pçcteci',
    'Pçcteèa ID',
    /* 1290 */
    'Pievienots "%1" pçctecis.',
    'Novâkts ¥%1¡ pçctecis.',
    'tiesîbas pievienot pçcteèus',
    'tiesîbas novâkt pçcteèus',
    'ziòot kad tiek pievienots pçctecis',
    'ziòot kad tiek novâkts pçctecis',
    'izveidotie ieraksti',
    'slçgtie ieraksti',
    'Konfidenciâls',
    'Pievienot konfidenciâlu komentâru',
    /* 1300 */
    'tiesîbas pievienot/lasît konfidenciâlos komentârus',
    'Tika pievienots konfidenciâls komentârs.',
    'Pirmsteèa ID',
    'atkarîba',
    'slçpts',
    'Pievienot atdalîtâju',
    'CSV Norobeþotâjs',
    'CSV kodçðana',
    'CSV rindu nobeigumi',
    'Meklçðanas rezultâti (nefiltrçti)',
    /* 1310 */
    'Ieslçgt filtrus',
    'Izslçgt filtrus',
    'Aktuâlâ filtru kopa',
    'Saglabât filtru kopu',
    'Filtru kopas',
    'Filtru kopas nosaukums',
    '"%1" filtru kopa',
    'Aktuâlais skatîjums',
    'Saglabât skatîjumu',
    'Izvçrst visu',
    /* 1320 */
    'Savçrst visu',
    'Atiestatît uz noklusçjumu',
    'P/N',
    'PCRE lauku vçrtîbu pârbaudei',
    'Meklçt PCRE lauku vçrtîbu mainîðanai',
    'Pârvietot PCRE lauku vçrtîbu mainîðana',
    'Nâkoðais stâvoklis pçc noklusçjuma',
    'Atlikðanas statuss',
    'râdît visu',
    'râdît tikai aktîvos',
    /* 1330 */
    'Notikums',
    'Nav filtru kopas',
    'Viesu piekïuve',
    'Nav.',
    '',
    'Viesis',
    'Imports',
    'tiesîbas dzçst ierakstus',
    'Autorizâcias tips',
    'Noklusçjuma valoda',
    /* 1340 */
    'Paroles derîguma termiòð (d.)',
    'Sesijas derîguma termiòð (min.)',
    'LDAP pârskaitîjums',
    'PostgreSQL',
    'indeksu saraksts',
    'vçrtîbu saraksts',
    'Izveidots',
    'Atzîmçt kâ izlasîtos',
    'Registered',  // TBT
    'TLS',
);

?>
