<?php

/**
 * Localization
 *
 * This module contains prompts translated in Polish.
 * All the prompts are in ISO-8859-2 encoding.
 *
 * @package Engine
 * @subpackage Localization
 * @author Rados³aw Wójtowicz
 */

//--------------------------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system.
//  Copyright (C) 2010 by Artem Rodygin
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//--------------------------------------------------------------------------------------------------
//  Author                  Date            Description of modifications
//--------------------------------------------------------------------------------------------------
//  Rados³aw Wójtowicz      2010-08-06      new-953: Polish localization.
//--------------------------------------------------------------------------------------------------

$resource_polish = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Wszystkie pola zaznaczone jako wymagane powinny byæ wype³nione.',
    'Warto¶æ domy¶lna powinna byæ z przedzia³u od %1 do %2.',
    'Konto jest wy³±czone.',
    'Konto jest zablokowane.',
    'Nieprawid³owa nazwa u¿ytkownika.',
    'Wprowadzona nazwa konta ju¿ istnieje.',
    'Nieprawid³owy adres email.',
    'Has³a nie s± identyczne.',
    'Has³o powinno mieæ co najmniej %1 znaków.',
    'Projekt o podanej nazwie ju¿ istnieje.',
    /* 210 */
    'Grupa o podanej nazwie ju¿ istnieje.',
    'Szablon o podanej nazwie lub prefixie ju¿ istnieje.',
    'Stan lub skrót o tej nazwie ju¿ istnieje.',
    'Pole o podanej nazwie ju¿ istnieje.',
    'Nieprawid³owa warto¶æ liczbowa',
    'Warto¶æ liczbowa powinna byæ z przedzia³u od %1 do %2.',
    'Warto¶æ "%1" powinna byæ z przedzia³u od %2 do %3.',
    'Warto¶æ maksymalna powinna byæ wiêksza od warto¶ci minimalnej.',
    'Zosta³ przekroczony limit "upload_max_filesize" w pliku konfiguracyjnym "php.ini".',
    'Wielko¶æ wysy³anego pliku nie mo¿e przekroczyæ %1 Kbytes.',
    /* 220 */
    'Przesy³any plik nie zosta³ do koñca przes³any.',
    'Nie przes³ano ¿adnego pliku.',
    'Brak tymczasowego folderu.',
    'Za³±cznik o podanej nazwie ju¿ istnieje.',
    'Nie znaleziono rekordu.',
    'Filtr o podanej nazwie ju¿ istnieje.',
    'Nieprawid³owa warto¶æ daty.',
    'Data powinna byæ z zakresu od %1 do %2.',
    'Nieprawid³owa warto¶æ czasu.',
    'Czas powinien byæ z zakresu od %1 do %2.',
    /* 230 */
    'Powiadomienie o tej samej nazwie ju¿ istnieje.',
    'Przypomnienie o tej samej nazwie ju¿ istnieje.',
    'Przypomnienie zosta³o wys³ane.',
    'Widok o tej samej nazwie ju¿ istnieje.',
    'Kolumna o tej samej nazwie ju¿ istnieje.',
    'B³±d zapisu na dysk.',
    'Upload pliku zosta³ zatrzymany przez ro¿sze¿enie.',
    'Musi byæ w³±czna obs³uga JavaScript.',
    'To jest automatycznie generowana wiadomo¶æ, proszê na ni± nie odpowiadaæ.',
    'Wybrany subrekord ju¿ istnieje.',
    /* 240 */
    'Ustawienia filtra o podanej nazwie ju¿ istniej±.',
    'Widok nie mo¿e mieæ wiêcej ni¿ %1 kolumn.',
    'Sprawdzenie warto¶ci "%1" nie powiod³o siê.',
    'U¿ytkownik nie uzyska³ autoryzacji.',
    'Nieprawid³owa nazwa u¿ytkownika lub has³a.',
    'Nieznana nazwa autoryzacji.',
    'Nieznany b³±d.',
    'B³±d parsowania XMLa.',
    'B³±d po³±czenia do bazy danych.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Czy jeste¶ pewien, ¿e chcesz usun±æ wszystkie widoki?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrane konto?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrany projekt?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybran± grupê?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrany szablon?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrany status?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrane pole?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrany rekord?',
    'Czy jeste¶ pewien, ¿e chesz wznowiæ wybrany rekord?',
    'Czy jeste¶ pewien, ¿e chesz przydzieliæ wybrany rekord?',
    /* 310 */
    'Czy jeste¶ pewien, ¿e chesz usun±æ wszystkie zaznaczone filtry?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wszytkie zaznaczone powiadomienia?',
    'Czy jeste¶ pewien, ¿e chesz wys³aæ wybrane przypomnienie?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybrane przypomnienie?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wybran± kolumnê?',
    'Czy jeste¶ pewien, ¿e chesz wyj¶æ?',
    'Czy jeste¶ pewien, ¿e chesz usun±æ wszystkie zaznaczone ustawienia filtrów?',
    'Czy jeste¶ pewien, ¿e chesz usn±æ wybrany rekord?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Polski',
    'Logowanie',
    '  OK  ',
    'Anuluj',
    'Zapisz',
    'Powrót',
    'Nastêpny',
    'Utwórz',
    'Edytuj',
    'Usuñ',
    /* 1010 */
    'Rekordy',
    'Konta',
    'Projekty',
    'Zmieñ has³o',
    'Pole o stausie "%1"',
    'brak',
    'Ilo¶æ:',
    'zapisz has³o',
    'Informacje o koncie',
    'Nazwa u¿ytkownika',
    /* 1020 */
    'Pe³na nazwa',
    'E-mail',
    'Prawa',
    'administrator',
    'u¿ytkownik',
    'Opis',
    'Has³o',
    'Potwierd¼ has³o',
    'wy³±czony',
    'zablokowany',
    /* 1030 */
    'Nowe konto',
    'Konto "%1"',
    'Informacje o projekcie',
    'Nazwa projektu',
    'Data utworzenia',
    'zawieszony',
    'Nowy projekt',
    'Projekt "%1"',
    'Grupy',
    'Informacje o grupie',
    /* 1040 */
    'Nazwa grupy',
    'Nowa grupa',
    'Grupa "%1"',
    'Cz³onkowie',
    'Inni',
    'Cz³onek',
    'Szablony',
    'Informacje o szablonie',
    'Nazwa szablonu',
    'Prefix',
    /* 1050 */
    'Nowy szablon',
    'Szablon "%1"',
    'Stany',
    'Informacja o stanie',
    'Nazwa stanu',
    'Skrót',
    'Typ stanu',
    'pocz±tkowy',
    'po¶redni',
    'koñcowy',
    /* 1060 */
    'Odpowiedzialny',
    'nie zmieniaj',
    'przydziel',
    'usuñ',
    'Nowy stan',
    'Stan "%1"',
    'Utwórz po¶redni',
    'Utwórz koñcowy',
    'Przej¶cia',
    'Uprawnienia',
    /* 1070 */
    'Utwórz pocz±tkowy',
    'Dozwolony',
    'Pola',
    'Informacje o polu',
    'Kolejno¶æ',
    'Nazwa pola',
    'Typ pola',
    'liczba',
    'tekst',
    'pole tekstowe',
    /* 1080 */
    'Wymagany',
    'tak',
    'nie',
    'Min.warto¶æ',
    'Max.warto¶æ',
    'Max.d³ugo¶æ',
    'wymagany',
    'Nowe pole (krok %1/%2)',
    'Pole "%1"',
    'Pozwolenie na odczyt',
    /* 1090 */
    'Pozwolenie do zapisu',
    'Informacje ogólne',
    'ID',
    'Projekt',
    'Szablon',
    'Stan',
    'Wiek',
    'Nowy rekord (krok %1/%2)',
    'Rekord "%1"',
    'Id¼',
    /* 1100 */
    'Historia',
    'Opó¼nij',
    'Wznów',
    'Przydziel',
    'Zmieñ status',
    'Czas',
    'Autor',
    'Rekord zosta³ utworzony ze statusem: "%1".',
    'Rekord zosta³ przypisany do %1.',
    'Rekord zosta³ zmodyfikowany.',
    /* 1110 */
    'Status zosta³ zmieniony do "%1".',
    'Rekord opó¼ni siê do %1.',
    'Rekord zosta³ wznowiony.',
    'Plik "%1" zosta³ do³±czony.',
    'Plik "%1" zosta³ usuniêty.',
    'pozwolenie na tworzenie rekordów',
    'pozwolenie na modyfikowanie rekordów',
    'pozwolenie na opó¼nianie rekordów',
    'pozwolenie na wznowienie rekordów',
    'pozwolenie na ponowne otwarcie rekordów',
    /* 1120 */
    'pozwolenie na zmiane statusu rekordu',
    'pozwolenie na do³±czanie plików',
    'pozwolenie na usuwanie plików',
    'Jêzyki',
    'Dodaj komentarz',
    'Komentarz zosta³ dodany.',
    'pozwolenie na dodawanie komentarzy',
    'Komentarz',
    'Dodaj plik',
    'Usuñ plik',
    /* 1130 */
    'Za³±cznik',
    'Nazwa za³±cznika',
    'Plik za³±cznika',
    'Za³±czniki',
    'Brak pól.',
    'Czas krytyczny',
    'Czas zamro¿enia',
    'Zmiany',
    'Poprzednia warto¶æ',
    'Nowa warto¶æ',
    /* 1140 */
    'checkbox',
    'rekord',
    'lista',
    'Pozycje listy',
    '%1 Kb',
    'Filtry',
    'Nazwa filtru',
    'Wszystkie projekty',
    'Wszystkie szablony',
    'Wszystkie stany',
    /* 1150 */
    'Poka¿ rekord',
    'Poka¿ tylko utworzone przez ...',
    'Poka¿ tylko przydzielone do ...',
    'poka¿ tylko nie zakoñczone',
    'Temat',
    'Szukaj',
    'Parametry wyszukiwania',
    'Wyniki wyszukiwania (filtrowane)',
    'Tekst który chesz wyszukaæ',
    'szukaj w polach',
    /* 1160 */
    'szukaj w komentarzach',
    'Status',
    'aktywny',
    'Powiadomienia',
    'powiadamiaj gdy utworzono nowy rekord',
    'powiadamiaj gdy przydzielono do rekordu',
    'powiadamiaj gdy rekord jest modyfikowany',
    'powiadamiaj gdy zmieni siê status rekordu',
    'powiadamiaj gdy rekord zostanie przesuniêty',
    'powiadamiaj gdy rekord jest wznowiony',
    /* 1170 */
    'powiadamiaj gdy zostanie dodany komentarz',
    'powiadamiaj gdy zostanie dodany za³±cznik',
    'powiadamiaj gdy plik zostanie usuniêty',
    'wymagany',
    'Przesuniêty',
    'Termin',
    'Waro¶æ domy¶lna',
    'w³±czony',
    'wy³±czony',
    'Statystyki',
    /* 1180 */
    'Otwartych rekordów',
    'Utworzonych do Zamknietych',
    'tydzieñ',
    'liczba',
    'Kopiuj',
    'Rekord zosta³ skopiowany z "%1".',
    'Wyloguj',
    'powiadamiaj je¶li rekord jest kopiowany',
    'Ustawienia',
    'Rekordów na stronie',
    /* 1190 */
    'Zak³adek na stronie',
    'Zablokuj',
    'Odblokuj',
    'Typ grupy',
    'globalna',
    'lokalna',
    'Konfiguracja',
    'Lokalna ¶cierzka',
    'Adres URL strony web',
    'Bezpieczeñstwo',
    /* 1200 */
    'Minimalna d³ugo¶æ has³a',
    'Maksymalna ilo¶æ prób zalogowania',
    'Czas blokowania (mins)',
    'Baza danych',
    'Typ bazy danych',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Serwer bazy danych',
    'Nazwa bazy danych',
    /* 1210 */
    'Nazwa u¿ytkownika bazy danych',
    'Active Directory',
    'Serwer LDAP',
    'Numer portu',
    'Konto szukania',
    'Podstawowy DN',
    'Administratorzy',
    'Powiadamianie przez email',
    'Maksymalna wielko¶æ',
    'Debugowanie',
    /* 1220 */
    'Tryb debugowania',
    'w³±czony (bez prywatnych danych)',
    'w³aczony (wszystkie dane)',
    'Debug logs',
    'W³±czony',
    'Wy³±czony',
    '%1 min',
    'pozwolenie na przegl±danie rekordów',
    'Zaznacz wszystko',
    'Autor',
    /* 1230 */
    'data',
    'czas',
    'poka¿ tylko przesuniête',
    'Nazwa powiadomienia',
    'Zdarzenia',
    'Wersja %1',
    'role',
    'Powiadamiaj',
    'Nie powiadamiaj',
    'Przypomnienia',
    /* 1240 */
    'Nazwa przypomnienia',
    'Tytu³ przypomnienia',
    'Odbiorcy przypomnienia',
    'Nowe przypomnienie (krok %1/%2)',
    'Przypomnienie "%1"',
    'pozwolenie do wysy³ania przypomnieñ',
    'Wy¶lij',
    'Nowy filtr',
    'Filtr "%1"',
    'Nowe powiadomienie',
    /* 1250 */
    'Powiadomienie "%1"',
    'Twoje has³o LDAP',
    'Mo¿esz wstawiæ link do innego rekordu wpisuj±c "rec#" i jego numer (np. "rec#305").',
    'Poka¿ tylko przeniesione do stanu ...',
    'Podziel siê z ...',
    'Eksportuj',
    'Inne powiadomienia...',
    'Dodany do powiadomieñ',
    '%1 doda³ Ciê do powiadomieñ dla wybranego rekordu.',
    '%1 zosta³ usuniêty z powiadamiania.',
    /* 1260 */
    'Kopia do',
    'Magazyn',
    'Arybuty LDAP',
    'Widoki',
    'Informacje o widoku',
    'Nazwa widoku',
    'Nowy widok (krok %1/%2)',
    'Widok "%1"',
    'Nie wybrano widoku',
    'Ustaw',
    /* 1270 */
    'Kolumny',
    'Informacja o kolumnie',
    'Nazwa kolumny',
    'Nowa kolumna',
    'Kolumna "%1"',
    'Wyrówanie',
    'z lewej',
    'wy¶rodkowane',
    'z prawej',
    'Us³uga bêdzie niedostêpna od %1 do %2 (%3)',
    /* 1280 */
    'Wszystkie przydzielone mi',
    'Wszystkie utworzone przeze mnie',
    'Odznacz wsystkie',
    'yyyy.m.d',
    'Zrzuæ',
    'Subrekordy',
    'Utwórz subrekord',
    'Do³±cz subrekord',
    'Usuñ subrekord',
    'Subrekord ID',
    /* 1290 */
    'Subrekord "%1" zosta³ dodany.',
    'Subrekord "%1" zosta³ usuniêty.',
    'pozwolenie na dodawnie subrekordów',
    'pozwolenie na usuwanie subrekordów',
    'powiadamiaj kiedy subrekord jest dodany',
    'powiadamiaj kiedy subrekord jest usuniêty',
    'utworzonych rekordów',
    'zamkniêtych rekordów',
    'Poufne',
    'Dodaj poufny komentarz',
    /* 1300 */
    'pozwolenie na dodawnie/czytanie poufnych komentarzy',
    'Poufny komentarz zosta³ dodany.',
    'Nadrzêdny ID',
    'zale¿ny',
    'ukryty',
    'Dodaj separator',
    'CSV znak rozdzielenia',
    'CSV kodowanie',
    'CSV zakoñczenie lini',
    'Wynik wyszukiwania (bez filtrów)',
    /* 1310 */
    'W³±cz filtry',
    'Wy³±cz filtry',
    'Bie¿±cy filtr',
    'Zapisz ustawienia filtrów',
    'Ustawienia filtrów',
    'Nazwa ustawienia filtra',
    'Ustaw filtry "%1"',
    'Bie¿±cy widok',
    'Zapisz widok',
    'Rozwiñ wszystkie',
    /* 1320 */
    'Zamknij wszystkie',
    'Przywróæ domy¶lne',
    'Ost.Mod.',
    'PCRE do sprawdzenia warto¶ci pola',
    'PCRE do przeszukiwania warto¶ci pola',
    'PCRE do zast±pienia warto¶ci pola',
    'Nastêpny status(domy¶lny)',
    'Status opó¼nienia',
    'poka¿ wszystkie',
    'poka¿ tylko aktywne',
    /* 1330 */
    'Zdarzenia',
    'Nie wybrano filtru',
    'Dostêp anonimowy',
    'Brak.',
    'Grupy globalne',
    'Go¶æ',
    'Import',
    'pozwolenie na kasowanie rekordów',
    'Rodzaj autoryzacji',
    'Domy¶lny jêzyk',
    /* 1340 */
    'Wyga¶niêcie has³a (dni)',
    'Wyga¶niêcie sesji (min)',
    'LDAP enumeration',
    'PostgreSQL',
    'lista indeksów',
    'lista warto¶ci',
    'Utworzony',
    'Zaznacz jako przeczytany',
    'Zarejestrowany',
    'TLS',
    /* 1350 */
    'Kompresja',
    'Ost.Stan',
);

?>
