<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2011  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Swedish.
 *
 * @package Engine
 * @subpackage Localization
 * @author Yan Ryberg
 */

$resource_swedish = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Alla fält markerade som obligatoriska måste fyllas i.',
    'Standardvärdet bör vara i intervallet från %1 till %2.',
    'Kontot är inaktiverat.',
    'Kontot är låst.',
    'Ogiltigt användarnamn.',
    'Kontot med detta användarnamn finns redan.',
    'Ogiltig email.',
    'Lösenorden matchar inte.',
    'Lösenord ska vara minst %1 tecken långt.',
    'Projekt med detta namnet finns redan.',
    /* 210 */
    'Grupp med detta namnet finns redan.',
    'Mall med detta namnet eller prefixet finns redan.',
    'Status med detta namnet eller förkortningen finns redan.',
    'Fält med detta namnet finns redan.',
    'Ogiltigt heltalsvärde.',
    'Heltal bör vara i intervallet från %1 till %2.',
    'Värdet av "%1" ska vara i intervallet från %2 till %3.',
    'Högsta värdet bör vara större än minimum en.',
    'Den uppladdade filen överskrider "upload_max_filesize" direktivet "php.ini".',
    'Storleken på uppladdade filen kan inte vara större än %1 Kbyte.',
    /* 220 */
    'Den uppladdade filen var endast delvis uppladdad.',
    'Ingen fil laddades upp.',
    'Saknar en tillfällig mapp.',
    'Bifogad fil med detta namnet finns redan.',
    'Journalen hittades inte.',
    'Filter med detta namnet finns redan.',
    'Ogiltigt datum.',
    'Datum bör vara i intervallet från %1 till %2.',
    'Ogiltigt tid.',
    'Tid bör vara i intervallet från %1 till %2.',
    /* 230 */
    'Prenumeration med detta namn finns redan.',
    'Påminnelse med detta namn finns redan.',
    'Påminnelse har skickats.',
    'Vyn med detta namn finns redan.',
    'Ange kort beskrivning av denna post.',
    'Misslyckades med att skriva till disken.',
    'Filuppladdningen stoppades av filendelsen.',
    'JavaScript måste vara påslaget.',
    'Detta är ett autogenererat meddelande, svara inte på det.',
    'Dina ändringar har sparats.',
    /* 240 */
    'Decimalvärdet ska vara från %1 till %2.',
    'Vyn kan inte ha mer än %1 kolumner.',
    'Värdet av "%1" misslyckades i format kontrollen.',
    'Användaren är inte godkänd.',
    'Okänt användarnamn eller felaktigt lösenord.',
    'Okänt fel.',
    'XML-parser fel.',
    NULL,

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Är du säker på att du vill ta bort alla valda vyer?',
    'Är du säker på att du vill ta bort detta kontot?',
    'Är du säker på att du vill ta bort detta projektet?',
    'Är du säker på att du vill ta bort denna gruppen?',
    'Är du säker på att du vill ta bort den här mallen?',
    'Är du säker på att du vill ta bort den här statusen?',
    'Är du säker på att du vill ta bort detta fältet?',
    'Är du säker på att du vill ändra status för denna post?',
    'Är du säker på att du vill återuppta denna post?',
    'Är du säker på att du vill återuppta denna post?',
    /* 310 */
    'Är du säker på att du vill ta bort alla valda filter?',
    'Är du säker på att du vill ta bort alla valda prenumerationer?',
    'Är du säker på att du vill skicka denna påminnelse?',
    'Är du säker på att du vill ta bort den här påminnelsen?',
    'Är du säker på att du vill avsluta?',
    'Är du säker på att du vill ta bort den här posten?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Svenska',
    'Logga in',
    'OK',
    'Avbryt',
    'Spara',
    'Tillbaka',
    'Nästa',
    'Skapa',
    'Ändra',
    'Ta bort',
    /* 1010 */
    'Poster',
    'Konton',
    'Projekt',
    'Ändra lösenord',
    'Fält med status "%1"',
    'inga',
    'Total:',
    'Tema',
    'Konto information',
    'Användarnamn',
    /* 1020 */
    'Fullständigt namn',
    'Email',
    'Standard',
    'administratör',
    'användare',
    'Beskrivning',
    'Lösenord',
    'Bekräfta lösenord',
    'inaktiverad',
    'låst',
    /* 1030 */
    'Nytt konto',
    'Konto "%1"',
    'Projekt information',
    'Projekt namn',
    'Start tid',
    'inaktiv',
    'Nytt projekt',
    'Projekt "%1"',
    'Grupper',
    'Grupp information',
    /* 1040 */
    'Grupp namn',
    'Ny Grupp',
    'Grupp "%1"',
    'Medlemskap',
    'Andra',
    'Medlemmar',
    'Mallar',
    'Mall information',
    'Mall namn',
    'Prefix',
    /* 1050 */
    'Ny mall',
    'Mall "%1"',
    'Status',
    'Status information',
    'Status namn',
    'Förkortning',
    'Status typ',
    'första',
    'mellanliggande',
    'slutlig',
    /* 1060 */
    'Ansvarig',
    'behåll oförändrad',
    'tilldela',
    'ta bort',
    'Ny status',
    'Status "%1"',
    'Skapa mellanliggande',
    'Skapa slutlig',
    'Övergångar',
    'Behörigheter',
    /* 1070 */
    'Gör första',
    'Tillåtna',
    'Fält',
    'Fält information',
    'Order',
    'Fält namn',
    'Fält typ',
    'nummer',
    'sträng',
    'flerraders text',
    /* 1080 */
    'Obligatorisk',
    'ja',
    'nej',
    'Min.värde',
    'Max.värde',
    'Max.längd',
    'obligatorisk',
    'Nytt fält (steg %1/%2)',
    'Fält "%1"',
    'skrivskyddad',
    /* 1090 */
    'läsa och skriva',
    'Allmän information',
    'ID',
    'Projekt',
    'Mall',
    'Status',
    'Ålder',
    'Ny post',
    'Post "%1"',
    'Mina poster',
    /* 1100 */
    'Historia',
    'Senarelägga',
    'Återuppta',
    'Tilldela',
    'Ändra status',
    'Tidsstämpel',
    'Upphovsman',
    'Posten är skapad med status "%1".',
    'Posten är tilldelad till %1.',
    'Posten är ändrad.',
    /* 1110 */
    'Status är ändrad till "%1".',
    'Posten är uppskjuten till %1.',
    'Posten är återupptagen.',
    'Filen "%1" är bifogad.',
    'Filen "%1" är borttagen.',
    'behörighet att skapa poster',
    'behörighet att ändra poster',
    'behörighet att senarelägga poster',
    'behörighet att återuppta poster',
    'behörighet att överlåta tilldelning poster',
    /* 1120 */
    'behörighet att ändra status för tilldelade poster',
    'behörighet att bifoga filer',
    'behörighet att ta bort filer',
    'Språk',
    'Lägg till kommentar',
    'Kommentar lades till.',
    'behörighet att lägga till kommentarer',
    'kommentar',
    'Bifogad fil',
    'Ta bort fil',
    /* 1130 */
    'Bifogad',
    'Bifogad namn',
    'Bifogad fil',
    'Bifogade',
    'Inga fält.',
    'Kritisk ålder',
    'Fryst tid',
    'Ändringar',
    'Gammalt värde',
    'Nytt värde',
    /* 1140 */
    'kryssruta',
    'post',
    'lista',
    'Listobjekt',
    '%1 Kb',
    'Filter',
    'Filter namn',
    'Alla projekt',
    'Alla mallar',
    'Alla statuser',
    /* 1150 */
    'Visa post',
    'Visa bara skapad av ...',
    'Visa bara tilldelad till ...',
    'visa bara ej avslutade',
    'Ämne',
    'Sök',
    'Sök parametrar',
    'Sök resultat',
    'Text att sökas igenom',
    'sök i fält',
    /* 1160 */
    'sök i kommentarer',
    'Status',
    'aktiv',
    'Prenumerationer',
    'meddela när post är skapad',
    'meddela när post är tilldelad',
    'meddela när post är ändrad',
    'meddela när status är ändrad',
    'meddela när post är senarelagd',
    'meddela när post är återupptagen',
    /* 1170 */
    'meddela när kommentarer lagts till',
    'meddela när en fil är bifogad',
    'meddela när en fil är borttagen',
    'obligatorisk',
    'Senarelagd',
    'Förfallodag',
    'Standardvärde',
    'på',
    'av',
    'Metrics',
    /* 1180 */
    'Öppnade poster',
    'Skapande vs Avslutande',
    'vecka',
    'nummer',
    'Klon',
    'Posten ar klonad från "%1".',
    'Logga ut',
    'meddela när post är klonad',
    'Inställningar',
    'Rader per sida',
    /* 1190 */
    'Bokmärken per sida',
    'Lås',
    'Lås upp',
    'Grupp typ',
    'global',
    'lokal',
    'Konfiguration',
    'Rad',
    'Webb rotsökväg',
    'Säkerhet',
    /* 1200 */
    'Minsta längd på lösenord ',
    'Maximalt antal inloggningsförsök',
    'Låsningstimeout (minuter)',
    'Databas',
    'Databas typ',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Databasserver',
    'Databas namn',
    /* 1210 */
    'Databasanvändare',
    'Active Directory',
    'LDAP server',
    'Port nummer',
    'Sök konto',
    'Bas DN',
    'Administratörer',
    'Email meddelande',
    'Maximal storlek',
    'Debug',
    /* 1220 */
    'Debug mode',
    'aktiverat (utan privata data)',
    'aktiverat (alla data)',
    'Debug loggar',
    'Aktiverad',
    'Inaktiverad',
    'decimal',
    'behörighet att endast visa poster',
    'Markera alla',
    'Upphovsman',
    /* 1230 */
    'datum',
    'varaktighet',
    'visa bara senarelagda',
    'Prenumerations namn',
    'Händelser',
    'Version %1',
    'roll',
    'Prenumera',
    'Avsluta prenumeration',
    'Påminnelse',
    /* 1240 */
    'Påminnelse namn',
    'Påminnelse ämne',
    'Påminnelse mottagare',
    'Ny påminnelse',
    'Påminnelse "%1"',
    'behörighet att skicka Påminnelse',
    'Skicka',
    'Nytt filter',
    'Filter "%1"',
    'Ny prenumeration',
    /* 1250 */
    'Prenumeration "%1"',
    'Antalet rader i flerraders fält',
    'Du kan infoga länk till en annan post genom att ange "rec#" och dess nummer (t.ex. "rec# 305").',
    'Visa endast flyttade till status ...',
    'Dela med ...',
    'Exportera',
    'Prenumerera andra...',
    'Prenumerera',
    '%1 har prenumererat dig till post.',
    '%1 har prenumererats.',
    /* 1260 */
    'Kopia',
    'Lagring',
    'LDAP attribut',
    'Vyer',
    'Stäng',
    'Vy namn',
    'Ny vy',
    'Vy "%1"',
    'Ingen vy',
    'Ställ in',
    /* 1270 */
    'Kolumner',
    'Varningar',
    'Information',
    'Fel',
    'Frågor',
    'Justering',
    'vänster',
    'centrera',
    'höger',
    'Tjänsten kommer att vara otillgänglig mellan %1 till %2 (%3)',
    /* 1280 */
    'Alla som tilldelats mig',
    'Alla som skapats av mig',
    'Visa i epost',
    'Var god vänta...',
    'Dump',
    'Underpost',
    'Create underpost',
    'Bifoga underpost',
    'Ta bort underpost',
    'Automatisk uppdateringsintervall',
    /* 1290 */
    'Underpost "%1" är tilllagd.',
    'Underpost "%1" är borttagen.',
    'behörighet att lägga till underposter',
    'behörighet att ta bort underposter',
    'meddela när underpost lagts till',
    'meddela när underpost är borttagen',
    'skapa post',
    'stängda poster',
    'Konfidentiellt',
    'Lägg till konfidentiell kommentar',
    /* 1300 */
    'behörighet att lägga till/läsa konfidentiella kommentarer',
    'Konfidentiell kommentar har lagts till.',
    'Förälder ID',
    'beroende',
    'Tidszon',
    'Lägg till separator',
    'CSV avgränsare',
    'CSV kodning',
    'CSV radslut',
    'meddela när posten öppnas igen',
    /* 1310 */
    'Aktivera filter',
    'Inaktivera filte',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Expandera alla',
    /* 1320 */
    'Komprimera alla',
    'Posten öppnas igen med status "%1".',
    'L/E',
    'PCRE för att kontrollera fältvärden',
    'Sök PCRE för att omvandla fältvärden',
    'Ersätt PCRE för att omvandla fältvärden',
    'Nästa status som standard',
    'Senarelägg status',
    'visa alla',
    'visa bara aktiva',
    /* 1330 */
    'Händelse',
    'Öppna',
    'Gäst åtkomst',
    'None.',
    'Globala grupper',
    'Gäst',
    'Importera',
    'behörighet att ta bort poster',
    NULL,
    'Standardspråk',
    /* 1340 */
    'Lösenordet upphör att gälla (dagar)',
    'Session avslutas (minuter)',
    'LDAP uppräkning',
    'PostgreSQL',
    'lista på index',
    'lista på värde',
    'Skapad',
    'Markera som läst',
    'Registrerad',
    'TLS',
    /* 1350 */
    'Komprimering',
    'L/S',
    'Kommentarer',
    'Storlek',
    'Utseende',
    'CSV',
    'Aktivera',
    'Inaktivera',
    'Förhandsgranska',
    'Ägare',
    /* 1360 */
    'Alla.',
    'Markera som oläst',
    'Föreldra post',
);

?>
