<?php

/**
 * Localization
 *
 * This module contains prompts translated in Turkish.
 * All the prompts are in ISO-8859-9 encoding.
 *
 * @package Engine
 * @subpackage Localization
 * @author Muhammet Kara
 */

//--------------------------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system.
//  Copyright (C) 2008-2010 by Artem Rodygin
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//--------------------------------------------------------------------------------------------------
//  Author                  Date            Description of modifications
//--------------------------------------------------------------------------------------------------
//  Muhammet Kara           2008-04-11      new-692: Turkish localization.
//  Muhammet Kara           2008-04-30      bug-699: Views // Names of custom columns are duplicated in the list of available columns, when there are two fields of different types with the same name.
//  Muhammet Kara           2008-05-01      new-715: Show creation time in the list of records.
//  Muhammet Kara           2008-08-14      new-729: [SF2008579] Mark all records as read
//  Muhammet Kara           2008-11-13      new-749: Guest access for unauthorized users.
//  Muhammet Kara           2009-01-09      new-774: 'Anyone' system role permissions.
//  Artem Rodygin           2009-04-12      bug-806: German translation causes two ambiguous "zuruck" buttons.
//  Artem Rodygin           2009-04-26      new-817: Field permissions dialog refactoring.
//  Artem Rodygin           2009-04-26      new-818: Change buttons layout on viewing record page.
//  Artem Rodygin           2009-10-12      new-848: LDAP TLS support.
//  Artem Rodygin           2009-10-12      new-837: Replace "Groups" with "Global groups" in main menu.
//  Artem Rodygin           2010-02-01      new-902: Transparent gzip compression of attachments
//--------------------------------------------------------------------------------------------------

$resource_turkish = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Gerekli olarak iþaretlenmiþ tüm alanlar doldurulmalýdýr.',
    'Varsayýlan deðer, %1 ile %2 arasýnda olmalýdýr.',
    'Hesap kapalý.',
    'Hesap kilitli.',
    'Geçersiz kullanýcý adý.',
    'Girilen kullanýcý adýyla bir hesap zaten var.',
    'Geçersiz e-posta.',
    'Parolalar uyuþmuyor.',
    'Parola en az %1 karakter uzunluðunda olmalýdýr.',
    'Girilen adda bir proje zaten var.',
    /* 210 */
    'Girilen adda bir grup zaten var.',
    'Girilen ad ya da ön ekle bir þablon zaten var.',
    'Girilen ad ya da kýsaltmayla bir durum zaten var.',
    'Girilen adda bir alan zaten var.',
    'Geçersiz tam sayý deðeri.',
    'Tam sayý deðeri %1 ile %2 arasýnda olmalýdýr.',
    '"%1" deðeri %2 ile %3 arasýnda olmalýdýr.',
    'En yüksek deðer, en düþük deðerden daha büyük olmalýdýr.',
    'Yüklenen dosya "php.ini"deki "upload_max_filesize" yönergesini aþýyor.',
    'Yüklenen dosyanýn boyutu %1 Kbytetan daha büyük olamaz.',
    /* 220 */
    'Yüklenen dosya sadece kýsmen yüklenmiþ.',
    'Hiç dosya yüklenmedi.',
    'Geçici bir klasör eksik.',
    'Girilen adda bir ek zaten var.',
    'Kayýt bulunamadý.',
    'Girilen adda bir filtre zaten var.',
    'Geçersiz tarih deðeri.',
    'Tarih deðeri %1 ile %2 arasýnda olmalýdýr.',
    'Geçersiz saat deðeri.',
    'Saat deðeri %1 ile %2 arasýnda olmalýdýr.',
    /* 230 */
    'Girilen adda bir abonelik zaten var.',
    'Girilen adda bir hatýrlatýcý zaten var.',
    'Hatýrlatýcý baþarýyla gönderildi.',
    'Girilen adda bir görünüm zaten var.',
    'Girilen adda bir sütun zaten var.',
    'Dosyanýn diske yazýmý baþarýsýz oldu.',
    'Dosya yüklemesi bir uzantý tarafýndan durduruldu.',
    'JavaScript etkin olmalýdýr.',
    'Bu otomatik bir mesajdýr, lütfen yanýtlamayýnýz.',
    'Belirtilen alt kayýt zaten var.',
    /* 240 */
    'Girilen adda bir filtreler kümesi zaten var.',
    'Görünümün sütun sayýsý %1 den fazla olamaz.',
    '"%1" deðeri biçim kontrolünü geçemedi.',
    'Kullanýcý yetkili deðil.',
    'Bilinmeyen kullanýcý adý ya da yanlýþ parola.',
    'Bilinmeyen kimlik doðrulama tipi.',
    'Bilinmeyen hata.',
    'XML ayrýþtýrýcý hatasý.',
    'Veri tabaný baðlantý hatasý.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Seçile tüm görünümleri silmek istediðinizden emin misiniz?',
    'Bu hesabý silmek istediðinizden emin misiniz?',
    'Bu projeyi silmek istediðinizden emin misiniz?',
    'Bu grubu silek istediðinizden emin misiniz?',
    'Bu þablonu silmek istediðinizden emin misiniz?',
    'Bu durumu silmek istediðinizden emin misiniz?',
    'Bu alaný silmek istediðinizden emin misiniz?',
    'Bu kaydý ertelemek istediðinizden emin misiniz?',
    'Bu kaydý devam ettirmek istediðinizden emin misiniz?',
    'Bu kaydý atamak istediðinizden emin misiniz?',
    /* 310 */
    'Seçilen tüm filtreleri silmek istediðinizen emin misiniz?',
    'Seçilen tüm abonelikleri silmek istediðinizden emin misiniz?',
    'Bu hatýrlatýcýyý göndermek istediðinizden emin misiniz?',
    'Bu hatýrlatýcýyý silmek istediðinizden emin misiniz?',
    'Bu sütunu silmek istediðinizden emin misiniz?',
    'Çýkmak istediðinizden emin misiniz?',
    'Seçilen tüm filtre kümelerini silmek istediðinizden emin misiniz?',
    'Bu kaydý silmek istediðinizden emin misiniz?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Türkçe',
    'Giriþ',
    '  Tamam  ',
    'Vazgeç',
    'Kaydet',
    'Geri',
    'Ýleri',
    'Oluþtur',
    'Deðiþtir',
    'Sil',
    /* 1010 */
    'Kayýtlar',
    'Hesaplar',
    'Projeler',
    'Parolayý deðiþtir',
    '"%1" durumunun alanlarý',
    'yok',
    'Toplam:',
    'parolayý kaydet',
    'Hesap bilgileri',
    'Kullanýcý adý',
    /* 1020 */
    'Tam adý',
    'E-posta',
    'Haklar',
    'yönetici',
    'kullanýcý',
    'Taným',
    'Parola',
    'Doðrulama',
    'kapalý',
    'kilitli',
    /* 1030 */
    'Yeni hesap',
    '"%1" hesabý',
    'Proje bilgileri',
    'Proje adý',
    'Baþlama zamaný',
    'askýda',
    'Yeni proje',
    '"%1" Projesi',
    'Gruplar',
    'Grup bilgileri',
    /* 1040 */
    'Grup adý',
    'Yeni grup',
    '"%1" grubu',
    'Üyelik',
    'Diðerleri',
    'Üyeler',
    'Þablonlar',
    'Þablon bilgileri',
    'Þablon adý',
    'Ön ek',
    /* 1050 */
    'Yeni þablon',
    '"%1" þablonu',
    'Durumlar',
    'Durum bilgileri',
    'Durum adý',
    'Kýsaltma',
    'Durum tipi',
    'ilk',
    'orta',
    'son',
    /* 1060 */
    'Sorumlu',
    'deðiþmeden kalan',
    'ata',
    'kaldýr',
    'Yeni durum',
    '"%1" Durumu',
    'Orta oluþtur',
    'Sonuç oluþtur',
    'Geçiþler',
    'Ýzinler',
    /* 1070 */
    'Ýlk yap',
    'Ýzin Verilen',
    'Alanlar',
    'Alan bilgileri',
    'Sýra',
    'Alan adý',
    'Alan tipi',
    'numara',
    'dizge',
    'çok satýrlý metin',
    /* 1080 */
    'Gerekli',
    'evet',
    'hayýr',
    'Min.deðer',
    'Maks.deðer',
    'Maks.uzunluk',
    'gerekli',
    'Yeni alan (adým: %1/%2)',
    '"%1" Alaný',
    'salt-okunur',
    /* 1090 */
    'okuma ve yazma',
    'Genel bilgiler',
    'ID',
    'Proje',
    'Þablon',
    'Durum',
    'Dönem',
    'Yeni kayýt (adým: %1/%2)',
    '"%1" Kaydý',
    'Git',
    /* 1100 */
    'Geçmiþ',
    'Ertele',
    'Devam Ettir',
    'Ata',
    'Durum deðiþtir',
    'Tarih bilgisi',
    'Çýkaran',
    'Kayýt, "%1" durumunda oluþturuldu.',
    'Kayýt, atandý: %1.',
    'Kayýt deðiþtirildi.',
    /* 1110 */
    'Durum, "%1" olarak deðiþtirildi.',
    'Kayýt, %1 tarihine ertelendi.',
    'Kayýt devam ettirildi.',
    '"%1" dosyasý eklendi.',
    '"%1" dosyasý kaldýrýldý.',
    'kayýtlar oluþturma izni',
    'kayýtlarý deðiþtirme izni',
    'kayýtlarý erteleme izni',
    'kayýtlarý devam ettirme izni',
    'atanmýþ kayýtlarý yeniden atama izni',
    /* 1120 */
    'atanmýþ kayýtlarýn durumunu deðiþtirme izni',
    'dosyalar ekleme izni',
    'dosyalarý kaldýrma izni',
    'Dil',
    'Yorum ekle',
    'Yorum eklendi.',
    'yorumlar ekleme izni',
    'Yorum',
    'Dosya ekle',
    'Dosyayý kaldýr',
    /* 1130 */
    'Ek',
    'Ek adý',
    'Ekli dosya',
    'Ekler',
    'Alan yok.',
    'Kritik dönem',
    'Dondurulmuþ zaman',
    'Deðiþen',
    'Eski deðer',
    'Yeni deðer',
    /* 1140 */
    'onay kutusu',
    'kayýt',
    'liste',
    'Ögeleri listele',
    '%1 Kb',
    'Filtreler',
    'Filtre adý',
    'Tüm projeler',
    'Tüm þablonlar',
    'Tüm durumlar',
    /* 1150 */
    'Kaydý göster',
    'Sadece þunun taafýndan oluþturulanlar: ...',
    'Sadece þuna atananlar: ...',
    'sadece kapanmamýþlarý göster',
    'Konu',
    'Ara',
    'Arama parametreleri',
    'Arama sonuçlarý (filtrelendi)',
    'Aranacak metin',
    'alanlarda ara',
    /* 1160 */
    'yorumlarda ara',
    'Durum',
    'aktif',
    'Abonelikler',
    'kayýt oluþturulduðu zaman haber ver',
    'kayýt atandýðý zaman haber ver',
    'kayýt deðiþtirildiði zaman haber ver',
    'durum deðiþtirildiði zaman haber ver',
    'kayýt ertelendiði zaman haber ver',
    'kayýt devam ettirildiði zaman haber ver',
    /* 1170 */
    'yorum eklendiði zaman haber ver',
    'dosya eklendiði zaman haber ver',
    'dosya kaldýrýldýðý zaman haber ver',
    'gerekli',
    'Ertelendi',
    'Son tarih',
    'Varsayýlan deðer',
    'açýk',
    'kapalý',
    'Metrik',
    /* 1180 */
    'Açýlan kayýtlar',
    'Kapanma\'ya karþý Oluþturma',
    'hafta',
    'numara',
    'Klonla',
    'Kayýt, "%1"den klonlanmýþ.',
    'Çýkýþ',
    'kayýt klonlandýðý zaman haber ver',
    'Ayarlar',
    'Sayfa baþýna satýrlar',
    /* 1190 */
    'Sayfa baþýna yer imleri',
    'Kilitle',
    'Kilidi Aç',
    'Grup tipi',
    'global',
    'yerel',
    'Yapýlandýrma',
    'Yerel kök yolu',
    'Web kök yolu',
    'Güvenlik',
    /* 1200 */
    'En az parola uzunluðu',
    'En fazla giriþ denemeleri sayýsý',
    'Kilitleme zaman aþýmý (dak.)',
    'Veri tabaný',
    'Veri tabaný tipi',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Veri tabaný sunucu',
    'Veri tabaný adý',
    /* 1210 */
    'Veri tabaný kullanýcýsý',
    'Aktif Dizin',
    'LDAP sunucu',
    'Port numarasý',
    'Hesap ara',
    'Temel DN',
    'Yöneticiler',
    'E-posta bildirimleri',
    'En fazla boyut',
    'Hata ayýkla',
    /* 1220 */
    'Hata ayýklama kipi',
    'etkinleþtirildi (özel veriler olmaksýzýn)',
    'etkinleþtirildi (tüm veriler)',
    'Hata ayýklama günlükleri',
    'Etkinleþtirildi',
    'Etkisizleþtirildi',
    '%1 dak',
    'sadece kayýtlarý görüntüleme izni',
    'Tümünü seç',
    'Yazar',
    /* 1230 */
    'tarih',
    'süre',
    'sadece ertelenmiþ olanlarý göster',
    'Abonelik adý',
    'Olaylar',
    'Sürüm: %1',
    'rol',
    'Abone ol',
    'Abonelikten ayrýl',
    'Hatýrlatýcýlar',
    /* 1240 */
    'Hatýrlatýcý adý',
    'Hatýrlatýcýnýn konusu',
    'Hatýrlatýcýyý alacaklar',
    'Yeni hatýrlatýcý (adým: %1/%2)',
    '"%1" Hatýrlatýcýsý',
    'hatýrlatýcýlar gönderme izni',
    'Gönder',
    'Yeni filtre',
    '"%1" Filtresi',
    'Yeni abonelik',
    /* 1250 */
    '"%1" Aboneliði',
    'LDAP parolanýz',
    '"rec#" ve numarasýný belirterek (ör: "rec#305") baþka bir kayda baðlantý ekleyebilirsiniz.',
    'Sadece durumlara taþýnanlarý göster: ...',
    'Þununla paylaþ: ...',
    'Dýþa aktar',
    'Baþkalarýný abone yap...',
    'Abone olundu',
    '%1 sizi kayda abone yaptý.',
    '%1 abonelikten ayrýldý.',
    /* 1260 */
    'Karbon kopya',
    'Bellek',
    'LDAP özniteliði',
    'Görüntülemeler',
    'Bilgileri görüntüle',
    'Adý görüntüle',
    'Yeni görüntüleme (adým: %1/%2)',
    '"%1" Görünümü',
    'Görünüm yok',
    'Ayarla',
    /* 1270 */
    'Sütunlar',
    'Sütun bilgileri',
    'Sütun baþlýðý',
    'Yeni sütun',
    '"%1" Sütunu',
    'Hizalama',
    'sol',
    'orta',
    'sað',
    '%1 ile %2 arasýnda hizmet verilemeyecektir (%3)',
    /* 1280 */
    'Bana atananlarýn tümü',
    'Benim tarafýmdan oluþturulanlarýn tümü',
    'Tümünün seçimini kaldýr',
    'm/d/yyyy',
    'Çöp',
    'Alt kayýtlar',
    'Alt kayýt oluþtur',
    'Alt kayýt ekle',
    'Alt kaydý kaldýr',
    'Alt kayýt kimlik no (ID)',
    /* 1290 */
    '"%1" alt kaydý eklendi.',
    '"%1" alt kaydý kaldýrýldý.',
    'alt kayýtlar ekleme izni',
    'alt kayýtlarý kaldýrma izni',
    'alt kayýt eklendiðinde haber ver',
    'alt kayýt kaldýrýldýðýnda haber',
    'oluþturulan kayýtlar',
    'kapatýlan kayýtlar',
    'Kiþiye özel',
    'Kiþiye özel yorum ekle',
    /* 1300 */
    'kiþiye özel yorumlar ekleme/okuma izni',
    'Kiþiye özel yorum eklendi.',
    'Ebeveyn kimlik no (ID)',
    'baðýmlýlýk',
    'saklý',
    'Ayraç ekle',
    'CSV sýnýrlayýcý',
    'CSV kodlama',
    'CSV satýr sonlarý',
    'Arama sonuçlarý (filtresiz)',
    /* 1310 */
    'Filtreleri etkinleþtir',
    'Filtreleri etkisizleþtir',
    'Þu anki filtre kümesi',
    'Filtre kümesini kaydet',
    'Filtre kümeleri',
    'Filtre kümesi adý',
    '"%1" filtre kümesi',
    'Þu anki görünüm',
    'Görünümü kaydet',
    'Tümünü geniþlet',
    /* 1320 */
    'Tümünü daralt',
    'Varsayýlanlara sýfýrla',
    'L/E',
    'Alan deðerlerini denetleyecek PCRE',
    'Alan deðerlerini dönüþtürecek PCRE ara',
    'Alan deðerlerini dönüþtürecek PCRE deðiþtir',
    'Varsayýlan olarak sonraki durum',
    'Durumu ertele',
    'tümünü göster',
    'sadece aktif olanlarý göster',
    /* 1330 */
    'Olay',
    'Filtre kümesi yok',
    'Konuk eriþimi',
    'Yok.',
    'Global gruplar',
    'Konuk',
    'Ýçe Aktar',
    'kayýtlarý silme izni',
    'Kimlik doðrulama tipi',
    'Varsayýlan dil',
    /* 1340 */
    'Parola zaman aþýmý (günler)',
    'Oturum zaman aþýmý (dak.)',
    'LDAP numaralamasý',
    'PostgreSQL',
    'numaralar listesi',
    'dizgeler listesi',
    'Oluþturuldu',
    'Okundu olarak iþaretle',
    'Kayýtlý',
    'TLS',
    /* 1350 */
    'Compression',  // TBT
);

?>
