<?php

//------------------------------------------------------------------------------
//
//  eTraxis - Records tracking web-based system
//  Copyright (C) 2008-2010  Artem Rodygin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//------------------------------------------------------------------------------

/**
 * Localization
 *
 * This module contains prompts translated in Turkish.
 *
 * @package Engine
 * @subpackage Localization
 * @author Muhammet Kara
 */

$resource_turkish = array
(
    RES_SECTION_ALERTS =>
    /* 200 */
    'Gerekli olarak işaretlenmiş tüm alanlar doldurulmalıdır.',
    'Varsayılan değer, %1 ile %2 arasında olmalıdır.',
    'Hesap kapalı.',
    'Hesap kilitli.',
    'Geçersiz kullanıcı adı.',
    'Girilen kullanıcı adıyla bir hesap zaten var.',
    'Geçersiz e-posta.',
    'Parolalar uyuşmuyor.',
    'Parola en az %1 karakter uzunluğunda olmalıdır.',
    'Girilen adda bir proje zaten var.',
    /* 210 */
    'Girilen adda bir grup zaten var.',
    'Girilen ad ya da ön ekle bir şablon zaten var.',
    'Girilen ad ya da kısaltmayla bir durum zaten var.',
    'Girilen adda bir alan zaten var.',
    'Geçersiz tam sayı değeri.',
    'Tam sayı değeri %1 ile %2 arasında olmalıdır.',
    '"%1" değeri %2 ile %3 arasında olmalıdır.',
    'En yüksek değer, en düşük değerden daha büyük olmalıdır.',
    'Yüklenen dosya "php.ini"deki "upload_max_filesize" yönergesini aşıyor.',
    'Yüklenen dosyanın boyutu %1 Kbytetan daha büyük olamaz.',
    /* 220 */
    'Yüklenen dosya sadece kısmen yüklenmiş.',
    'Hiç dosya yüklenmedi.',
    'Geçici bir klasör eksik.',
    'Girilen adda bir ek zaten var.',
    'Kayıt bulunamadı.',
    'Girilen adda bir filtre zaten var.',
    'Geçersiz tarih değeri.',
    'Tarih değeri %1 ile %2 arasında olmalıdır.',
    'Geçersiz saat değeri.',
    'Saat değeri %1 ile %2 arasında olmalıdır.',
    /* 230 */
    'Girilen adda bir abonelik zaten var.',
    'Girilen adda bir hatırlatıcı zaten var.',
    'Hatırlatıcı başarıyla gönderildi.',
    'Girilen adda bir görünüm zaten var.',
    NULL,
    'Dosyanın diske yazımı başarısız oldu.',
    'Dosya yüklemesi bir uzantı tarafından durduruldu.',
    'JavaScript etkin olmalıdır.',
    'Bu otomatik bir mesajdır, lütfen yanıtlamayınız.',
    NULL,
    /* 240 */
    NULL,
    'Görünümün sütun sayısı %1 den fazla olamaz.',
    '"%1" değeri biçim kontrolünü geçemedi.',
    'Kullanıcı yetkili değil.',
    'Bilinmeyen kullanıcı adı ya da yanlış parola.',
    'Bilinmeyen hata.',
    'XML ayrıştırıcı hatası.',

    RES_SECTION_CONFIRMS =>
    /* 300 */
    'Seçile tüm görünümleri silmek istediğinizden emin misiniz?',
    'Bu hesabı silmek istediğinizden emin misiniz?',
    'Bu projeyi silmek istediğinizden emin misiniz?',
    'Bu grubu silek istediğinizden emin misiniz?',
    'Bu şablonu silmek istediğinizden emin misiniz?',
    'Bu durumu silmek istediğinizden emin misiniz?',
    'Bu alanı silmek istediğinizden emin misiniz?',
    NULL,
    'Bu kaydı devam ettirmek istediğinizden emin misiniz?',
    'Bu kaydı atamak istediğinizden emin misiniz?',
    /* 310 */
    'Seçilen tüm filtreleri silmek istediğinizen emin misiniz?',
    'Seçilen tüm abonelikleri silmek istediğinizden emin misiniz?',
    'Bu hatırlatıcıyı göndermek istediğinizden emin misiniz?',
    'Bu hatırlatıcıyı silmek istediğinizden emin misiniz?',
    'Çıkmak istediğinizden emin misiniz?',
    'Bu kaydı silmek istediğinizden emin misiniz?',

    RES_SECTION_PROMPTS =>
    /* 1000 */
    'Türkçe',
    'Giriş',
    'Tamam',
    'Vazgeç',
    'Kaydet',
    'Geri',
    'İleri',
    'Oluştur',
    'Değiştir',
    'Sil',
    /* 1010 */
    'Kayıtlar',
    'Hesaplar',
    'Projeler',
    'Parolayı değiştir',
    '"%1" durumunun alanları',
    'yok',
    'Toplam:',
    'Tema',
    'Hesap bilgileri',
    'Kullanıcı adı',
    /* 1020 */
    'Tam adı',
    'E-posta',
    'Öntanımlı',
    'yönetici',
    'kullanıcı',
    'Tanım',
    'Parola',
    'Doğrulama',
    'kapalı',
    'kilitli',
    /* 1030 */
    'Yeni hesap',
    '"%1" hesabı',
    'Proje bilgileri',
    'Proje adı',
    'Başlama zamanı',
    'askıda',
    'Yeni proje',
    '"%1" Projesi',
    'Gruplar',
    'Grup bilgileri',
    /* 1040 */
    'Grup adı',
    'Yeni grup',
    '"%1" grubu',
    'Üyelik',
    'Diğerleri',
    'Üyeler',
    'Şablonlar',
    'Şablon bilgileri',
    'Şablon adı',
    'Ön ek',
    /* 1050 */
    'Yeni şablon',
    '"%1" şablonu',
    'Durumlar',
    'Durum bilgileri',
    'Durum adı',
    'Kısaltma',
    'Durum tipi',
    'ilk',
    'orta',
    'son',
    /* 1060 */
    'Sorumlu',
    'değişmeden kalan',
    'ata',
    'kaldır',
    'Yeni durum',
    '"%1" Durumu',
    'Orta oluştur',
    'Sonuç oluştur',
    'Geçişler',
    'İzinler',
    /* 1070 */
    'İlk yap',
    'İzin Verilen',
    'Alanlar',
    'Alan bilgileri',
    'Sıra',
    'Alan adı',
    'Alan tipi',
    'numara',
    'dizge',
    'çok satırlı metin',
    /* 1080 */
    'Gerekli',
    'evet',
    'hayır',
    'Min.değer',
    'Maks.değer',
    'Maks.uzunluk',
    'gerekli',
    'Yeni alan (adım: %1/%2)',
    '"%1" Alanı',
    'salt-okunur',
    /* 1090 */
    'okuma ve yazma',
    'Genel bilgiler',
    'ID',
    'Proje',
    'Şablon',
    'Durum',
    'Dönem',
    'Yeni kayıt',
    '"%1" Kaydı',
    'Kayıtlarım',
    /* 1100 */
    'Geçmiş',
    'Ertele',
    'Devam Ettir',
    'Ata',
    'Durum değiştir',
    'Tarih bilgisi',
    'Çıkaran',
    'Kayıt, "%1" durumunda oluşturuldu.',
    'Kayıt, atandı: %1.',
    'Kayıt değiştirildi.',
    /* 1110 */
    'Durum, "%1" olarak değiştirildi.',
    'Kayıt, %1 tarihine ertelendi.',
    'Kayıt devam ettirildi.',
    '"%1" dosyası eklendi.',
    '"%1" dosyası kaldırıldı.',
    'kayıtlar oluşturma izni',
    'kayıtları değiştirme izni',
    'kayıtları erteleme izni',
    'kayıtları devam ettirme izni',
    'atanmış kayıtları yeniden atama izni',
    /* 1120 */
    'atanmış kayıtların durumunu değiştirme izni',
    'dosyalar ekleme izni',
    'dosyaları kaldırma izni',
    'Dil',
    'Yorum ekle',
    'Yorum eklendi.',
    'yorumlar ekleme izni',
    'Yorum',
    'Dosya ekle',
    'Dosyayı kaldır',
    /* 1130 */
    'Ek',
    'Ek adı',
    'Ekli dosya',
    'Ekler',
    'Alan yok.',
    'Kritik dönem',
    'Dondurulmuş zaman',
    'Değişen',
    'Eski değer',
    'Yeni değer',
    /* 1140 */
    'onay kutusu',
    'kayıt',
    'liste',
    'Ögeleri listele',
    '%1 Kb',
    'Filtreler',
    'Filtre adı',
    'Tüm projeler',
    'Tüm şablonlar',
    'Tüm durumlar',
    /* 1150 */
    'Kaydı göster',
    'Sadece şunun taafından oluşturulanlar: ...',
    'Sadece şuna atananlar: ...',
    'sadece kapanmamışları göster',
    'Konu',
    'Ara',
    'Arama parametreleri',
    'Arama sonuçları',
    'Aranacak metin',
    'alanlarda ara',
    /* 1160 */
    'yorumlarda ara',
    'Durum',
    'aktif',
    'Abonelikler',
    'kayıt oluşturulduğu zaman haber ver',
    'kayıt atandığı zaman haber ver',
    'kayıt değiştirildiği zaman haber ver',
    'durum değiştirildiği zaman haber ver',
    'kayıt ertelendiği zaman haber ver',
    'kayıt devam ettirildiği zaman haber ver',
    /* 1170 */
    'yorum eklendiği zaman haber ver',
    'dosya eklendiği zaman haber ver',
    'dosya kaldırıldığı zaman haber ver',
    'gerekli',
    'Ertelendi',
    'Son tarih',
    'Varsayılan değer',
    'açık',
    'kapalı',
    'Metrik',
    /* 1180 */
    'Açılan kayıtlar',
    'Kapanma\'ya karşı Oluşturma',
    'hafta',
    'numara',
    'Klonla',
    'Kayıt, "%1"den klonlanmış.',
    'Çıkış',
    'kayıt klonlandığı zaman haber ver',
    'Ayarlar',
    'Sayfa başına satırlar',
    /* 1190 */
    'Sayfa başına yer imleri',
    'Kilitle',
    'Kilidi Aç',
    'Grup tipi',
    'global',
    'yerel',
    'Yapılandırma',
    'Yerel kök yolu',
    'Web kök yolu',
    'Güvenlik',
    /* 1200 */
    'En az parola uzunluğu',
    'En fazla giriş denemeleri sayısı',
    'Kilitleme zaman aşımı (dak.)',
    'Veri tabanı',
    'Veri tabanı tipi',
    'Oracle',
    'MySQL',
    'Microsoft SQL Server',
    'Veri tabanı sunucu',
    'Veri tabanı adı',
    /* 1210 */
    'Veri tabanı kullanıcısı',
    'Aktif Dizin',
    'LDAP sunucu',
    'Port numarası',
    'Hesap ara',
    'Temel DN',
    'Yöneticiler',
    'E-posta bildirimleri',
    'En fazla boyut',
    'Hata ayıkla',
    /* 1220 */
    'Hata ayıklama kipi',
    'etkinleştirildi (özel veriler olmaksızın)',
    'etkinleştirildi (tüm veriler)',
    'Hata ayıklama günlükleri',
    'Etkinleştirildi',
    'Etkisizleştirildi',
    NULL,
    'sadece kayıtları görüntüleme izni',
    'Tümünü seç',
    'Yazar',
    /* 1230 */
    'tarih',
    'süre',
    'sadece ertelenmiş olanları göster',
    'Abonelik adı',
    'Olaylar',
    'Sürüm: %1',
    'rol',
    'Abone ol',
    'Abonelikten ayrıl',
    'Hatırlatıcılar',
    /* 1240 */
    'Hatırlatıcı adı',
    'Hatırlatıcının konusu',
    'Hatırlatıcıyı alacaklar',
    'Yeni hatırlatıcı',
    '"%1" Hatırlatıcısı',
    'hatırlatıcılar gönderme izni',
    'Gönder',
    'Yeni filtre',
    '"%1" Filtresi',
    'Yeni abonelik',
    /* 1250 */
    '"%1" Aboneliği',
    NULL,
    '"rec#" ve numarasını belirterek (ör: "rec#305") başka bir kayda bağlantı ekleyebilirsiniz.',
    'Sadece durumlara taşınanları göster: ...',
    'Şununla paylaş: ...',
    'Dışa aktar',
    'Başkalarını abone yap...',
    'Abone olundu',
    '%1 sizi kayda abone yaptı.',
    '%1 abonelikten ayrıldı.',
    /* 1260 */
    'Karbon kopya',
    'Bellek',
    'LDAP özniteliği',
    'Görüntülemeler',
    NULL,
    'Adı görüntüle',
    'Yeni görüntüleme',
    '"%1" Görünümü',
    'Görünüm yok',
    'Ayarla',
    /* 1270 */
    'Sütunlar',
    NULL,
    NULL,
    NULL,
    NULL,
    'Hizalama',
    'sol',
    'orta',
    'sağ',
    '%1 ile %2 arasında hizmet verilemeyecektir (%3)',
    /* 1280 */
    'Bana atananların tümü',
    'Benim tarafımdan oluşturulanların tümü',
    'Tümünün seçimini kaldır',
    'm/d/yyyy',
    'Çöp',
    'Alt kayıtlar',
    'Alt kayıt oluştur',
    'Alt kayıt ekle',
    'Alt kaydı kaldır',
    'Alt kayıt kimlik no (ID)',
    /* 1290 */
    '"%1" alt kaydı eklendi.',
    '"%1" alt kaydı kaldırıldı.',
    'alt kayıtlar ekleme izni',
    'alt kayıtları kaldırma izni',
    'alt kayıt eklendiğinde haber ver',
    'alt kayıt kaldırıldığında haber',
    'oluşturulan kayıtlar',
    'kapatılan kayıtlar',
    'Kişiye özel',
    'Kişiye özel yorum ekle',
    /* 1300 */
    'kişiye özel yorumlar ekleme/okuma izni',
    'Kişiye özel yorum eklendi.',
    'Ebeveyn kimlik no (ID)',
    'bağımlılık',
    NULL,
    'Ayraç ekle',
    'CSV sınırlayıcı',
    'CSV kodlama',
    'CSV satır sonları',
    NULL,
    /* 1310 */
    'Filtreleri etkinleştir',
    'Filtreleri etkisizleştir',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Tümünü genişlet',
    /* 1320 */
    'Tümünü daralt',
    NULL,
    'S/O',
    'Alan değerlerini denetleyecek PCRE',
    'Alan değerlerini dönüştürecek PCRE ara',
    'Alan değerlerini dönüştürecek PCRE değiştir',
    'Varsayılan olarak sonraki durum',
    'Durumu ertele',
    'tümünü göster',
    'sadece aktif olanları göster',
    /* 1330 */
    'Olay',
    NULL,
    'Konuk erişimi',
    'Yok.',
    'Global gruplar',
    'Konuk',
    'İçe Aktar',
    'kayıtları silme izni',
    NULL,
    'Varsayılan dil',
    /* 1340 */
    'Parola zaman aşımı (günler)',
    'Oturum zaman aşımı (dak.)',
    'LDAP numaralaması',
    'PostgreSQL',
    'numaralar listesi',
    'dizgeler listesi',
    'Oluşturuldu',
    'Okundu olarak işaretle',
    'Kayıtlı',
    'TLS',
    /* 1350 */
    'Sıkıştırma',
    'S/D',
    'Yorumlar',
    'Boyut',
    'Görünüm',
    'CSV',
    'Etkinleştir',
    'Devre dışı bırak',
    'Önizleme',
    'Sahibi',
    /* 1360 */
    'Herkes.',
    'Okunmadı olarak işaretle',
    'Ebeveyn kayıtları',
);

?>
